### ISSUE TITLE
C# tutorial project throws error that it is missing F# assemblies

### ISSUE THREAD

**Issue by didii** [picoe/Eto#1011]
## Expected Behavior
Running the tutorial `CS.Tutorial1.HelloWorld` runs without errors and is not dependent on F#.

## Actual Behavior
An error is thrown that it cannot run because the assembly `System.Core.FSharp` is missing.
Full exception message:

> `System.IO.FileNotFoundException: 'Could not load file or assembly 'FSharp.Core, Version=4.4.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.'`

## Steps to Reproduce the Problem

If you have FSharp installed you'll probably need to uninstall them first. I have never installed it. I think you should be able to uninstall it unchecking via Visual Studio Installer > Modify > Summary > .Net desktop development > F# desktop language support.

  1. Make a fresh clone of the project
  2. Build and run `CS.Tutorial1.HelloWorld`
  3. The exception shows up
    a. Notice that the stack trace refers to `FS.Tutorial1.HelloWorld.Program`

I have noticed that sometimes the exceptions happens in the F# file itself or in the `Eto.Wpf.Platform` (or another `Platform` class, can't seem to reproduce it now) class at adding an `ApplicationHandler`.

## Current workaround

  1. Go to the property page of `CS.Tutorial1.HelloWorld`
    a. Right click the project
    b. Click Properties
  2. Set Startup object to Tutorial1.Program
  3. Save, build and run `CS.Tutorial1.HelloWorld`
  4. The issue is now permanently fixed
    a. Setting the Startup object back to (not set) will not make the issue appear again.

## Code that Demonstrates the Problem
N/A

## Specifications

  - Version: latest development commit (12b10f9e)
  - Platform(s): WPF, WinForms
  - OS: Windows 10
  - IDE: Visual Studio 2017

**Comment by cwensley** [comment]
Thanks for reporting the issue!  I think it's actually because the F# and C# projects were outputting to the same assembly name.  So, when you were trying to run the C# project it was actually trying to run the F# compiled assembly.  

Your fix to update the project setting probably just prompted VS to rebuild that particular project so that it started to work.  If you removed that project setting it would probably still run.

I've fixed it by changing the output assembly name instead.  Please let me know if you still run into issues!
