### ISSUE TITLE
Tree grid of drawable cells

### ISSUE THREAD

**Issue by JonSargent** [picoe/Eto#1251]
Hi all,

What is the proper way to compose a TreeGridView out of DrawableCells?  

My question probably reveals an underlying confusion about what a Cell is.  I would expect a grid (Tree or otherwise) to comprise a 2D array of Cells, but instead it appears to comprise a 1D array of GridItems, which have one or more _values_.  In the case of TextBoxCells, I see that I can seed the values for each row with strings, e.g.

    DataStore = new TreeGridItemCollection
    {
        new TreeGridItem("string(0,0)", "string(0,1)"),
        new TreeGridItem("string(1,0)", "string(1,1)")
    };

...but how would I do this for my DrawableCells (presuming the value of relevance is, say, a Color)?  What if the DrawableCell has more than one parameter? e.g.

    public class MyCell : DrawableCell
    {
        public string Text;
        public Color Color;      

        public MyCell(string text, Color color)
        {
            Text = text;
            Color = color;
        }

        protected override void OnPaint(CellPaintEventArgs e)
        {
            // custom stuff
        }
    }

Maybe I'm barking up the wrong tree (pun intended) and should just draw my own table? I was hoping to take advantage of the expanding/collapsing function of the TreeGridView, though.

Thanks,

Jon

**Comment by cwensley** [comment]
Hey @JonSargent,

Thanks for the question.  In Eto, there is only one instance of the Cell class, which is used to specify what _type_ of cell is used for that column.

So, you wouldn't have the `text` or `color` properties in the class or in the constructor.  In the OnPaint method, you get the item and the value(s) you are interested in.  For example:

```c#
public class MyCell : DrawableCell
{
    protected override void OnPaint(CellPaintEventArgs e)
    {
        var item = e.Item as TreeGridItem;
        var value0 = item.Values[0] as string;
        var value1 = item.Values[1] as Color;

       // do custom stuff.
    }
}
```

.. assuming something like this:
```c#
DataStore = new TreeGridItemCollection
{
    new TreeGridItem("string(0,0)", Colors.Blue),
    new TreeGridItem("string(1,0)", Colors.Red)
};
```

If you like type safety, you can subclass `TreeGridItem` and add your own properties to it for each value you need, instead of using the `Values` collection.

**Comment by JonSargent** [comment]
Ah, beautiful 👍

Thanks @cwensley !
