### ISSUE TITLE
The ProgressBar disappears

### ISSUE THREAD

**Issue by DWAK-ATTK** [picoe/Eto#1264]
So I wrote an app that displays a ProgressBar.  This app is being run on macOS.

When I run the app from the project output directory, everything works as expected.

However when I copy the app to the Desktop and run it, the ProgressBar is missing. (All other UI elements are present (Menu, Toolbar w/ 3 buttons and icons, Labels in a TableLayout).

If I then copy the app to the Applications directory and run it, it runs as expected, showing the ProgressBar.

If I create an alias on the Desktop pointing to the app in the Applications directory (just drag the app from Applications to Desktop) and launch the app via the alias, the ProgressBar is AWOL.

If this were a YA book it's be called "The Mystery of the Disappearing ProgressBar".  heh.

Anyhow, thoughts on why this is happening?  Other thoughts on how to avoid it?

**Comment by DWAK-ATTK** [comment]
I installed the app on a different MBP today - that one running macOS 10.13.4 (High Sierra)
and the problem does not appear to be present there.

The one I am experiencing this problem on is my development MBP running macOS 10.14.1 (Mojave).

I don't know where to start looking for a cause.

**Comment by cwensley** [comment]
Hm, the only thing I can think of is that macOS is caching the application executable, which I have run into some times (when the version, identifier, and path are the same).  You may be actually running an older version of your app.

What I do to get around this is rename the .app e.g. "My App.app" to "My App 2.app".  Give it a try to see if that helps.

Otherwise, there's nothing I can think of that would cause this.

**Comment by DWAK-ATTK** [comment]
I'll keep an eye on that.  Thanks.
