### ISSUE TITLE
Eto.Forms.Dialog very slow

### ISSUE THREAD

**Issue by tkdogan** [picoe/Eto#1371]
I just recently converted my Rhino6 C# plugin interfaces from WPF to Eto.Forms. I am using Eto.Forms.Dialog extensively. The layouts are simple but contain many controls (dropdowns and text boxes). The ShowModal() function seems to be very slow and the dialog only shows up a few seconds after a button click in Grasshopper / Rhino6.
Is there a trick to speed up the Eto interfaces or a best practice regarding display performance for Eto that I might be missing?

```
// builds a nested layout with tab controls and pages with about 100 controls (text boxes, radio buttons, dropdowns etc.) each
     inputForm = new DialogEnergyResults(settings, ref resSet);
// this takes longest and seems to be causing the main delay.
     inputForm.ShowModal();
```

**Comment by cwensley** [comment]
Hey @tkdogan,

Thanks for submitting the issue!  We have a number of complex forms that have been created that don't appear to exhibit the same behaviour as you are noticing, though you may be doing some things that we haven't been doing thus far, such as having (numerous) DropDown and/or TabControl controls.

If most of the delay appears in ShowModal(), it is most likely the WPF layout and measuring that is causing the largest slowdown.

The DropDown has an additional performance impact when using it with Eto as its preferred size is dependent on all items it contains.  This is not the default with native WPF applications, as it changes its size depending only on the selected item.  Having a large number of DropDown controls with a large number of items each would slow the time it takes to initially show the form/dialog.  One way to speed up initial display in this case could be to only populate all items when the `DropDown.DropDownOpening` event is triggered. 

Also in Eto (vs. WPF), the TabControl measures _all_ tabs for auto sizing the form not just the currently selected tab for auto sizing purposes.  There isn't much you can do do here unfortunately other than breaking up your form into different child dialogs instead of a single monolithic dialog.

If you could share an example of a form that exhibits the problems you're having, I may be able to provide some additional suggestions (or hopefully to get Eto to deal with it more efficiently).

I hope this helps!

**Comment by TomQv** [comment]
>  it is most likely the WPF layout and measuring that is causing the largest slowdown.

I can only confirm this. Thats why I use Eto source to patch several dirty hacks to reduce the number of layout cycles. 99% are unnecessary and just slowing down the ui, only the last one counts. WPF has a mechanism SuspendLayout and ResumeLayout, which I believe is intended to speed up thinks when changing forms and controls but Eto is not making use of this.

Most of these problems are not reproducible in small demo-projects, but only occuring in complex conditions.

On Mac I have none of these problems, with same app.

**Comment by cwensley** [comment]
Hey @TomQv,

> WPF has a mechanism SuspendLayout and ResumeLayout, which I believe is intended to speed up thinks when changing forms and controls but Eto is not making use of this.

I think you might be thinking of WinForms.  WPF does not have SuspendLayout and ResumeLayout as far as I know.  For WPF, all of the measuring is done in `FrameworkElement.MeasureOverride`, which is only executed once when the dialog is shown.

**Comment by TomQv** [comment]
Its called different in wpf, for example https://stackoverflow.com/questions/82847/in-wpf-what-is-the-equivalent-of-suspend-resumelayout-and-backgroundworker?noredirect=1&lq=1

But I have no clue, if and how its really working

**Comment by tkdogan** [comment]
@TomQv would you be able to share some of your workarounds? Or is this something that is likely to be fixed in upcoming Eto versions?

**Comment by TomQv** [comment]
For example for us it was a huge performance plus to delete this line::
`Control.LayoutUpdated += Control_LayoutUpdated;`
in Eto.Wpf.Forms.TableLayoutHandler.TableLayoutHandler.CreateControl

Other thing is to delete the MeasureOverride- and ArrangeOverride-overrides in Eto.Wpf.Forms.Controls.ScrollableHandler.EtoScrollViewer.

Its just try-and-error. I didn't notice negative effects from these changes yet for our project. I came up with these things with code-profiling, trying to identify where the most time is spend in code-execution.

**Comment by cwensley** [comment]
Is this still an issue?  A lot of work has been done to make Eto integrate better with WPF's layout system (since this was reported) so it does much less work.  If not please provide an example of a dialog that exhibits the problem and I can look into it further.

**Comment by tkdogan** [comment]
It looks like things have gotten better. I deactivated text wrap on all labels and noticed that this improved things quite a bit.
