### ISSUE TITLE
ItemTextBinding Update

### ISSUE THREAD

**Issue by hschmiedhofer** [picoe/Eto#1396]
I am using ETO with Rhinoceros3D and C# on Windows10. 

I am wiring a ListBox as follows:
```
_separatorLister.DataStore = this._vm_as_parameter.Separators;
_separatorLister.SelectedValueBinding.BindDataContext((ViewModelCupboardFrame vm) => vm.SelectedSeparator);
_separatorLister.ItemTextBinding = Eto.Forms.Binding.Delegate<ViewModelCupboardSeparator, string>((ViewModelCupboardSeparator vmbd) => vmbd.Name);
_separatorLister.SelectedValueChanged += SeparatorLister_SelectedValueChanged;
```

Now, even though the DataStore's items' names are changing, they are not exchanged with ItemTextBinding. Updating the bindings of the ListBox (in either direction) does not work.

Even adding and removing items from the ListBox does not seem to call the ItemTextBinding delegate again.

What can I do to update names in my list?

**Comment by cwensley** [comment]
@hschmiedhofer sorry for the late reply (I respond on the clock on discourse.mcneel.com though).  It is not setting the value because you are using a Delegate binding without a setter.. For example, this might work:

`Eto.Forms.Binding.Delegate<ViewModelCupboardSeparator, string>((ViewModelCupboardSeparator vmbd) => vmbd.Name, (m, v) => m.Name = v);`

However, you could also use the property binding which finds the setter automatically:
`Eto.Forms.Binding.Property((ViewModelCupboardSeparator vmbd) => vmbd.Name);`

Hope this helps!
