### ISSUE TITLE
Help understanding commands and how to use them

### ISSUE THREAD

**Issue by Shadowblitz16** [picoe/Eto#1405]
Hello, I recently tried this for a native cross platform GUI and was wondering about commands.
I am mainly wondering what they are exactly and how to use them? 
however I also was wondering is there was a such thing as event callbacks in Eto?

I am used to being able to do things like..
`ButtonMenuItem.Clicked += OnClicked()` and handling them in the hook.

can you explain what is the benefit of using Commands over events and how?
what exactly are commands and how are they declared and linked to a certain object and how do I know what they are going to do?

**Comment by SlowLogicBoy** [comment]
You can still do 
`ButtonMenuItem.Clicked += OnClicked()`
the difference is that you need to pass that `OnClicked` method to `ButtonMenuItem` [constructor](http://api.etoforms.picoe.ca/html/M_Eto_Forms_ButtonMenuItem__ctor_2.htm):
`new ButtonMenuItem(OnClicked)`.

To see benefits of using Commands you can read up about [Command design pattern](https://en.wikipedia.org/wiki/Command_pattern).
Simple Command code:
```csharp
Command SaveCommand = new Command(OnSave);

private void OnSave(object sender, EventArgs e) {
    if (!IsChanged) return;
    _repository.SaveModelDefinition(GetModel());
}
```
I  guess main Command benefit is that you can separate logic from other classes ([Single Responsibility Principle](https://en.wikipedia.org/wiki/Single_responsibility_principle)) and reuse that command in multiple places:
```csharp
public class SaveCommand : Command {
    private readonly IMyRepository _repository;

    public SaveCommand(IMyRepository repository) {
        MenuText = "Save";
        ToolBarText = "Save";
        Image = Res.SaveImage;
        ToolTip = "Save your project";

        _repository = repository;
    }
    
    protected override void OnExecuted(EventArgs e) {
        _repository.SaveMyChanges();
    }
}
```
Also in Eto if you have command you no longer need to create `ButtonMenuItem` yourself because command can be converted to one:
```csharp
Menu = new MenuBar{
    Items = {
        new SaveCommand(MyRepository)
    }
};
```
Also Command is responsible for itself, so it can check if it's [enabled](http://api.etoforms.picoe.ca/html/P_Eto_Forms_Command_Enabled.htm) this can be done ether with [binding](https://github.com/picoe/Eto/wiki/Data-Binding) or overriding [OnDataContextChanged](http://api.etoforms.picoe.ca/html/M_Eto_Forms_Command_OnDataContextChanged.htm) method and update `Enabled` property when `Command.DataContext` object changes.

**Comment by Shadowblitz16** [comment]
thank you so much for explaining. 
I am going to use commands

**Comment by cwensley** [comment]
Thanks for the question, and thanks @SlowLogicBoy for the excellent answer.  You can also use commands to bind to `Button.Command`, `ButtonMenuItem.Command`, etc when using MVVM patterns.

For example:

```c#
class MyViewModel
{
  public Command MyCommand => new Command(SomeHandler);
  void SomeHandler(object sender, EventArgs e)
  {
    // do some logic, use MyCommand.Enabled to enable/disable the command, etc.
  }
}

class MyView : Panel
{
  public MyView()
  {
    var button = new Button { Text = "Click Me!" };
    button.BindDataContext(c => c.Command, (MyViewModel m) => m.MyCommand);

    Content = new StackLayout { Items = { button } };

    DataContext = new MyViewModel(); // usually set by whomever creates MyView
  }
}
```

Hope this helps!
Curtis.

**Comment by Shadowblitz16** [comment]
@cwensley I still don't understand how commands tie to events in controls.

how do I tell the difference between a command execute when a button is pressed and when it is hovered over?

A better example would be how I draw onto a picturebox if I need OnMouseMove, OnMouseEnter, OnMouseExit, OnMouseDown, and OnMouseUp commands to do so?

**Comment by cwensley** [comment]
@Shadowblitz16 a command is triggered when the button is clicked and can enable/disable the UI. It has nothing to do with the other events.  Use the other events directly on those controls if you want to use them.

**Comment by Shadowblitz16** [comment]
@cwensley 
shouldn't it be called PressedCommand then so it a little more clear on what it does?

**Comment by cwensley** [comment]
A Command is "an instruction or signal that causes a computer to perform one of its basic functions.".  So, when the user clicks on something it will "command" the app to do something tangible.  MouseEnter and other events are not a command, they are events.

**Comment by Shadowblitz16** [comment]
ok ty
