### ISSUE TITLE
Style Differences from WinFroms

### ISSUE THREAD

**Issue by Shadowblitz16** [picoe/Eto#1423]
Style Differences between EtoForms and WinForms on Windows 7 Home 64 bit

![image](https://user-images.githubusercontent.com/2453707/58768074-fb7eaa80-8549-11e9-9309-8392704b888e.png)

is there a way to update EtoForms to look more like the Winforms Style?
If anyone can post a picture of WinXp, Win8, Win10 It would be appreciated.

as for linux and mac users I can't say much since winforms doesn't look native on them.

**Comment by cwensley** [comment]
The style is different because by default the Eto.Forms templates use WPF on windows.

If you want to have the same style as winforms, you can use the Eto.WinForms platform (Eto.Platform.Windows nuget package).  In your startup code, you can select it via:

```c#
new Application(Eto.Platforms.WinForms).Run(new MainForm());
```

If you want WPF to look different, you can apply WPF styles to the windows via [native styles](https://github.com/picoe/Eto/wiki/Styling) in your WPF launcher.  This would probably be an exercise in frustration so just using the Eto.WinForms platform may be more ideal for you if you want it to look (exactly) like WinForms.

Hope this helps!

**Comment by Shadowblitz16** [comment]
is there a way to support `Eto.Platforms.Detect` with winforms?
I want to do cross platform gui development but I prefer winforms over wpf.

**Comment by cwensley** [comment]
@Shadowblitz16 yes, just don't include Eto.Platforms.Wpf in your project.

**Comment by Shadowblitz16** [comment]
awesome thankyou

**Comment by cwensley** [comment]
You’re welcome!

**Comment by Shadowblitz16** [comment]
@cwensley  can this be reopened I can't get Eto.Windows to work.
maybe a project for vs 2017 and 2019 that uses winforms instead of wpf?

Edit: got it working with separate projects but it still isn't native looking
![image](https://user-images.githubusercontent.com/2453707/65395659-d9a47000-dd52-11e9-888e-9ee18605a93c.png)
[EtoAppTest2.zip](https://github.com/picoe/Eto/files/3640264/EtoAppTest2.zip)
