### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by LaraSQP** [picoe/Eto#1497]
First, my heartfelt thanks to Curtis for taking the time to develop and make available this awesome project.

Having said that, I see very few commits, hardly any support, and no community to speak of.

The error could be mine but, is this project dead?

**Comment by cwensley** [comment]
Hey @LaraSQP, thanks for the inquiry.

I'm not sure how many commits a project would need to be considered "alive", but given there have been commits [almost every week in the past year](https://github.com/picoe/Eto/graphs/commit-activity), I'd say that would be a clear sign that it is not dead.  

Also, in the [past month](https://github.com/picoe/Eto/pulse/monthly) there's been 6 merged PR's, 4 new issues, and 6 closed issues.  Not a lot, but why would it need a lot?  Wouldn't that be a sign of a poor design, missing features, or a buggy framework?

One message I've heard from developers is that they don't submit issues or request features or are generally inactive in the community because Eto.Forms does what they need.

This project is used in commercial applications and others that are used every day, and companies are paying money to make Eto.Forms better.

I'm not sure what else you would want from a project, but I hope this sheds some light on its current status.

**Comment by LaraSQP** [comment]
Thank you for the quick reply.

I am delighted to hear the error is mine and will proceed to recommend to my manager that we give Eto a try for our Linux and Mac ports.
