### ISSUE TITLE
Default vs2019 project does not run on Linux (attached)

### ISSUE THREAD

**Issue by LaraSQP** [picoe/Eto#1594]
I'm guessing it is a setup problem with `Core 3.1`. The `wpf` executable runs fine on `Windows`.

On `Linux` though, the error is:
`Cannot open assembly 'EtoApp2.Gtk.exe': File does not contain a valid CIL image.`

## Specifications

  - Version: 2.5.0
  - Platform(s): Mono 6.8.0 Stable (6.8.0.105)
  - Operating System(s): Ubuntu 18.04.3

**Comment by LaraSQP** [comment]
Forgot to attach it.

[EtoApp2.zip](https://github.com/picoe/Eto/files/4242630/EtoApp2.zip)

**Comment by LaraSQP** [comment]
Using the old `NETStandard.Library` setup works, that is, `1.6.1` is ok but `2.0.3` yields the error above.

**Comment by cwensley** [comment]
With .Net Core, .exe's are windows-only.  You are getting an .exe most likely because you are compiling on windows.  You need to use `dotnet run MyApp.dll` instead of using the exe.  If you compile on linux, you would get an executable for linux (with no extension).

Please read up on [publishing for .net core](https://docs.microsoft.com/en-us/dotnet/core/deploying/deploy-with-cli) on how to publish your app for a particular platform, with or without the .net core runtime included.

**Comment by LaraSQP** [comment]
Much appreciated.

**Comment by cwensley** [comment]
Any time, glad to help.  I hope to get some of the documentation updated soon to point people in the right direction when starting out.
