### ISSUE TITLE
DocumentControl is not shown until there are more than 1 DocumentPages (Linux)

### ISSUE THREAD

**Issue by LaraSQP** [picoe/Eto#1608]
On Linux, `DocumentControl` is not shown until there are more than **one** `DocumentPages`.

When a second `DocumentPage` is added, both are displayed.

Note that the content of the `DocumentPage` is always shown. It is just the tab itself that is missing.

Wpf works as expected.

**Comment by hxbb00** [comment]
gtk Platform appear too

**Comment by cwensley** [comment]
Hm it appears this was the intended behaviour, though it does not make sense to do so if you want to allow the last document to be closed. 

I added a property to the handler to restore the previous behaviour for those that need it. 

This should be fixed in the latest CI build and will be included in the 2.5.3 release.

**Comment by LaraSQP** [comment]
Thank you for resolving this.
