### ISSUE TITLE
Support for Mapping solution (OSM or google maps)

### ISSUE THREAD

**Issue by trampster** [picoe/Eto#1625]
I am hoping to include a mapping feature in my Group Push to Talk application (Ropu) which will show the location of other members of your group. (opt in of course)

But I can't find any information about how to do this with Eto.Forms. Has anyone done this yet, is there a nuget package or similar which will give me this support.

If not how would one best go about including maps in Eto.Forms.

Finally are there any plans to make mapping a part of Eto.Forms?

**Comment by ManuelHu** [comment]
The best way I can think of: Use `Eto.Forms.WebView` with some locally hosted static HTML files. 
There you can include [Leaflet](https://leafletjs.com/) which is a JavaScript library to include OpenStreetMap maps, create markers etc. Your wrapper can be quite shallow, and you should be able to inject and execute JavaScript code from inside your Eto app.

Probably you don't want to use GoogleMaps APIs anyway, because as far as I know, you need to provide payment information to get an API key (and you probably don't want be charged money for your users actions...) The approach would be similar to OSM, I suppose.

**Comment by cwensley** [comment]
Thanks for the suggestion.  Using the WebView is certainly your best option right now.  I've added an issue to Eto.Toolkit to track this, so I'm closing the issue here.
