### ISSUE TITLE
FileVersionInfo.GetVersionInfo throws exception on Mac

### ISSUE THREAD

**Issue by LaraSQP** [picoe/Eto#1633]
The code below works as expected in Windows and Linux but, perhaps obviously, crashes on `Mac`:

	var assemblyDll = Assembly.GetExecutingAssembly();
	var versionInfo = FileVersionInfo.GetVersionInfo( assemblyDll.Location );

How does one get the `Package` information (e.g., `ProductVersion`, `LegalCopyright`, `ProductName`, etc) in Mac?

**Comment by cwensley** [comment]
@LaraSQP if you're using .NET Core, it's because of [this](https://github.com/dotnet/runtime/issues/13051).  If you're using mono, it's because of mkbundle which has similar consequences. (location is null).

With Eto, you should be able to use `EtoEnvironment.GetFolderPath(EtoSpecialFolder.ApplicationResources)` instead, which will give the .exe path on windows, and the Resources folder of a macOS bundle.  Set your file to 'Content' in VS to get it put in the right spot.

However, I have not tested that API in this situation, so if they do not return a path please let me know.

**Comment by LaraSQP** [comment]
Appreciate the quick reply and, btw, awesome work with Mac. Eto rocks.

Now, how does it make sense to put a dll in the Resources folder?

I am using NetStandard here.

**Comment by LaraSQP** [comment]
Per the code above, `assemblyDll.Location` returns the name of the `dll` but not its path, that is, it returns its filename alone, which is insufficient for `GetVersionInfo` to work.

At this point, my workaround is to generate a text file with the assembly information and add that text file to the `Resources` as `Content`.

**Comment by cwensley** [comment]
Thanks for the follow up.

Another way to get at these is to use `var assemblyVersion = myAssembly.GetCustomAttribute<AssemblyVersionAttribute>()` etc.

I don't think there'll ever be a way to use `FileVersionInfo` if the .dll doesn't actually exist on disk.

**Comment by LaraSQP** [comment]
I got this working alike and as expected in Mac, Linux, and Windows:

	var assembly	= typeof( MainForm ).Assembly;

	var Product	= assembly.GetCustomAttribute<AssemblyProductAttribute>()?.Product;
	var Description = assembly.GetCustomAttribute<AssemblyDescriptionAttribute>()?.Description;
	var Company	= assembly.GetCustomAttribute<AssemblyCompanyAttribute>()?.Company;
	var Copyright	= assembly.GetCustomAttribute<AssemblyCopyrightAttribute>()?.Copyright;
	var Version	= assembly.GetCustomAttribute<AssemblyFileVersionAttribute>()?.Version;
	var Version2	= assembly.GetName()?.Version;

	_TextArea.Text	= $"Product: {Product}\nDescription: {Description}\nCompany {Company}\nCopyright: {Copyright}\nVersion: {Version}";
	_TextArea.Text	+= $"\nVersion2: {Version2.Major}.{Version2.Minor}";

Thanks for the tip.
