### ISSUE TITLE
App fails to start under macOS

### ISSUE THREAD

**Issue by morphx666** [picoe/Eto#1756]
I'm compiling the application under Windows using the following settings:
- Single Windows, Linux and Mac desktop projects
- Full .NET Framework
- Code Preview

This Windows machine has mono 6.10.0 x64 installed.

When trying to run the App from macOS High Sierra 10.13.6, I can see the icon bouncing on the dock for a few seconds and then it disappears, without producing any error messages.

**Comment by cwensley** [comment]
Hey @morphx666, this is probably because of a few things (executable bit and downloading an unsigned/non-notarized app).  See https://github.com/picoe/Eto/wiki/Troubleshooting-and-Common-Problems#problem-the-app-bundle-application-compiled-on-windows-does-not-run-on-mac on how to get around those for development purposes, and links to information about signing/notarizing your app for macOS when you are ready to distribute your app.

Also, #1748 might be of interest to you (after I do it), I would like to automate this process, at least when compiling on macOS.

**Comment by morphx666** [comment]
Thank you VERY much @cwensley 
That was the solution, which I obviously forgot about from my past project... sorry!
