### ISSUE TITLE
[GTK] Inconsistent scrollbar behaviour on a WebView

### ISSUE THREAD

**Issue by Miepee** [picoe/Eto#1895]
Hello, first time opening an issue here, so I'm sorry in advance if I miss anything here.

My WebView element has a website loaded, that has Custom CSS.

## Expected Behavior
The scrollbar shouldn't be affected by it, and look like according to the default theme selected.

## Actual Behavior
The scrollbar is inconsistent. It flashes its colours, depending on if the cursor is currently hovering over it or not.
And in the Console GTK is complaining. The warning message is:
`(WebKitWebProcess:18629): Gtk-WARNING **: 10.54.26.907: Theme parsing error: colors.css:77:65: Invalid number for a color value`

## Media
https://streamable.com/2zyzox

## Steps to Reproduce the Problem

  1. Implement a WebView that loads a website with custom CSS.
  2. Export to GTK (I was using Eto.Platforms.GTK here, which from my understanding uses GTK3. I haven't tested it on GTK2.)
  3. Notice the scrollbar, hover over it and notice the difference

## Code that Demonstrates the Problem

```cs
Content = new TableLayout
{
    Rows =       
        new WebView
        {
            Url = new Uri("https://lojemiru.github.io/DistributionCenter/changelog.html")
        }
    }
}
```

## Specifications
  - Target Framework: Happens on both .NET Framework 4.8 and .NET Core 5.0
  - Version: Eto: 2.5.10
  - Platform(s): Eto.Platforms.GTK 2.5.10
  - Operating System(s): Tested on a Linux Mint 20.04 VM with different themes. Including, Mint-y, Breeze and emacs. Used both XFCE and KDE as desktop environments, but no change was between them

**Comment by cwensley** [comment]
Hey @Miepee, thanks for reporting the issue.  However, this looks like "correct" behaviour to me, the scrollbar changes when you hover over it so you can scroll, just like other controls (at least on Ubuntu).   It does not "fade" like standard controls, perhaps because it does it differently.  

For example, this is what it looks like on Ubuntu when hovering over it:

<img width="901" alt="Screen Shot 2021-02-17 at 9 15 31 AM" src="https://user-images.githubusercontent.com/367446/108241574-d60c4880-7100-11eb-8272-9cd89cbf8abb.png">

Compare to the scrollbar on the TreeGridView when hovering:

<img width="901" alt="Screen Shot 2021-02-17 at 9 15 44 AM" src="https://user-images.githubusercontent.com/367446/108241542-cd1b7700-7100-11eb-8e21-aced0be0c245.png">


It definitely has issues with your theme given the warning.. maybe it doesn't support the alpha channel for the web view scroll bar..

At any rate, this does not appear to be a problem with Eto, and would need to be fixed in WebKit2GTK+.

Hope this helps.

Cheers,
Curtis.

**Comment by Miepee** [comment]
Thanks for the reply.
Actually, my issue was more with the fact, that the scrollbar gets themed at all (you can see a very dark scrollbar in my linked video above, something that is abscent in your pictures). On GTK, Browsers (like Firefox for example), or on other platforms (so far only tested win10) the scrollbar does not theme itself to the site, I'd expect it for the WebView to behave the same.
So I'd rather have it for consistency's sake, so that the Platforms have the same scrollbar behaviour. Because asking the Website's owner to change their scrollbar css, just so the scrollbar looks consistent on GTK is not always an approach I could take.
You could also see it as an Accessibilty Problem :P

**Comment by cwensley** [comment]
I do see the dark scrollbar too if I move the mouse over the WebView though it fades away after some time (like other controls).  It looks like it does that if the background color of the page is dark.

I hear you on trying to change the scrollbar appearance to be more like the other controls, but this is not something that appears can be fixed in Eto.

There is [this api](https://webkitgtk.org/reference/webkit2gtk/stable/WebKitWebContext.html#webkit-web-context-set-use-system-appearance-for-scrollbars), but it is actually already turned on by default.  Turning it off doesn't appear to do anything.. 🤦🏻‍♂️

You'll have to talk with the webkit2gtk folks to see if there is anything that can be done.

**Comment by Miepee** [comment]
Hm, all right then. Thanks for answering.
I'll close the issue then, since Eto can't do nothing about it.
