### ISSUE TITLE
Eto.Forms Support Addin not works on monodevelop-7x

### ISSUE THREAD

**Issue by fabiuz** [picoe/Eto#2031]
In monodevelop-5.10.0-19.fc34.x86_64 the addin "Eto.Forms" works normally, but, on monodevelop-7.8.4.1-0.xamarin.1.epel8.x86_64 not works, this error below have occurred:
Eto.Forms Support Addin
Version 2.3.0.6

**_The followring dependencies required by this extension package are not available:
Required: MonoDevelop.Core v6.0, found v7.8.4
Required: MonoDevelop.Ide v6.0, found v7.8.4_**

My configuration:
MonoDevelop
Version 7.8.4 (build 2)
Installation UUID: ae41882d-3277-47ea-9a54-c35123889bbc
	GTK+ 2.24.33 (Adwaita theme)

Mono Framework MDK
Runtime:
	Mono 6.12.0.107 (tarball Wed Dec  9 21:44:58 UTC 2020) (64-bit)

NuGet
Version: 4.8.2.5835

.NET Core
Runtime: /usr/share/dotnet/dotnet
Runtime Version: 5.0.10
SDK: /usr/share/dotnet/sdk/5.0.401/Sdks
SDK Version: 5.0.401
MSBuild SDKs: /usr/lib/mono/msbuild/15.0/bin/Sdks

Build Information
Release ID: 708040002
Git revision: 622db12503514afdb641c31615408bfe905a7312
Build date: 2019-07-17 17:02:07-04

Operating System
Linux
Linux 5.13.12-200.fc34.x86_64 #1 SMP Wed Aug 18 13:27:18 UTC 2021 x86_64

Enabled user installed extensions
MonoGame Extension 3.8.0.1641
D Language Binding 2.14.5
MonoGame Addin 3.6.0.586
Eto.Forms Support Addin 2.3.0.6
JSON Copy 1.1
.NET Core support for Mono.Debugging 7.8.2
Paket 0.5
MSBuild Editor 2.1.0
AddinMaker 1.4.3
C# Interactive 1.0

**Comment by cwensley** [comment]
Hi @fabiuz,

Thanks for reporting the issue.  The Eto.Forms extension for MonoDevelop is no longer supported, since monodevelop is not supported either.  I would recommend using VSCode on linux, along with the [vscode-mono-debug](https://marketplace.visualstudio.com/items?itemName=ms-vscode.mono-debug) extension if you're creating a mono-based application, and the [C# extension](https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.csharp) for .NET Core/5 applications.

This being said, an older version of the Eto.Forms extension _might_ work with MonoDevelop 7.x on linux, which you have to download from the [releases](https://github.com/picoe/Eto/releases) on GitHub.

**Comment by cwensley** [comment]
BTW, looks like [Eto's 2.4.1 release](https://github.com/picoe/Eto/releases/2.4.1) _should_ support MonoDevelop 7.x

**Comment by cwensley** [comment]
In case there was any doubt, https://github.com/mono/monodevelop has been archived.  Closing the issue as there's no point supporting obsolete software.

**Comment by surfzoid** [comment]
hi
monodevelop is now dotdevelop
https://github.com/dotdevelop/dotdevelop

**Comment by cwensley** [comment]
@surfzoid cool!  I like to see that happening.  Let me know when it's got an official release and we can see what we can do to support it.
