### ISSUE TITLE
ObjectListView with Eto.Forms

### ISSUE THREAD

**Issue by devmaestro1** [picoe/Eto#2153]
Hello,

I am looking at the potential of using [ObjectListView](http://objectlistview.sourceforge.net/cs/index.html) with Eto.Forms as it's an awesome control that allows a mix of tree and list view controls (along with a intuitive way of adding items). 

Does anyone know of any project that has already tried to implement this control into Eto.Forms or make it cross-platform compatible? From what I understand, there are native Windows calls in it.

If there is no such project, can anyone comment on what sort of work would be involved in converting the project to Eto.Forms? Would it be just a matter of namespace re-naming, fixing bugs and then dealing with the native calls? Or can someone see there being a blocker to it? Obviously I don't want to start analyzing this in-depth unless there is a hope it will work...

Thanks for any input.

**Comment by rafntor** [comment]
That would be a great thing for sure !
The native windows-specific things are collected nicely in [one place](https://github.com/devmaestro1/ObjectListView/blob/main/ObjectListView/Implementation/NativeMethods.cs) and is manageable. Some of those are probably readily available in Eto.Forms already (like GetClientRect & SetWindowPos) and therefore can be replaced with non-native code. Others may be tricky or even impossible to do xplat ; I guess it's hard to say without diving into it.
A big problem for some would be the GPL-3 license with this library, perhaps an approach is to write it from scratch with another license and take inspiration from the things it achieve instead of taking the code outright ;-)

I actually considered the same as you at one point but the GPL made me not pursue it

**Comment by devmaestro1** [comment]
Thanks for your input @rafntor. I hadn't considered the licensing yet. I wouldn't mind open sourcing it if there was enough interest. Pending some further possible replies on this, I might take a deeper look at the ObjectListView code and see. With a bit of luck, maybe someone has already done something similar  ;)

**Comment by cwensley** [comment]
Hey @devmaestro1,

Thanks for submitting the request. 

Other than the grouping, Eto's GridView and TreeGridView could probably be cajoled into doing a lot of what that control does, though I have not looked into it deeply.  However, it would help if you were more specific on exactly what you'd like to achieve that GridView/TreeGridView does not already so we can turn them into actionable issues or provide guidance on how it could be done.

I'm going to close this as it isn't feasible nor license friendly.  Please feel free to open other issues/discussions for any specific functionality you are looking for that Eto does not provide.

**Comment by devmaestro1** [comment]
Thanks, @cwensley. I think you are correct that "core" visual/layout functionality is covered by ListView, however ObjectListView's ease-of-use is its real value add. Rather than poking and prodding the ListView (as the developer puts it), you are instead using callbacks to display rows and images from the dataset. It's very intuitive and flexible once you get the hang of it and opens up lots of rendering possibilities with a few lines of code.

It's a design shift so I imagine if it were ever implemented as part of the Eto suite, it would need to be a separate control. From @rafntor's response, it looks like other people have contemplated it but no one has ventured there yet.

I will update this thread if I get any further information... and hopefully anyone will add to it if they have attempted a conversion  ;)
