### ISSUE TITLE
Add ability to have closable tabs

### ISSUE THREAD

**Issue by keepwn** [picoe/Eto#225]
When i using winform, if i wanna close one tabpage, i can double click to close, or override the onpaint func to add close button in tab.

But in eto, i could not find the doubleclick event in tabtitle.
If override to add close button in tab, i think it will spend a lot of time. (I am not good at monomac.)
How should i do?

**Comment by cra0zy** [comment]
I can make a PR that implements this for Gtk if it helps (someone else would need to implement it for the other backends)

**Comment by cwensley** [comment]
The problem with this, is that on macOS, this is not the 'desired' way to do it.. Using the existing TabControl would get you some strange UI, and on top of that, you can't add custom controls to each tab (e.g. close button).  

However, now with macOS Sierra _all_ apps now have built-in ability to use tabs so this control is probably not even needed there so you can use `Platform.Supports<DocumentTabControl>()` to determine if its supported by the platform before using it.  Otherwise, if we really do want this capability as a control on macOS, we'll need to build a fully custom control (e.g. via Drawable, etc).

I have thought that perhaps a Drawable-based tab control would be more ideal here, even on all platforms so we can provide more flexibility on how its used e.g. it wouldn't necessarily need to tie in the content of each tab, and that could be tied in by specifying a panel or using another control that combines the custom tabs and a panel to hold the content.

What do you think?

**Comment by cra0zy** [comment]
I've seen that macOS implemented tabs for all applications, but I'm not sure how they work, and can they even be used with something like Xamarin Studio which requires tabs to be within interface.

Now I wouldn't like implementing Drawable based tab control for all platforms because Gtk already has a way of how it should look (ie. Gedit: https://blogs.gnome.org/nacho/files/2014/01/gedit2.png, easily achievable with GtkNotebook), bit I think that would be alright on other platforms that don't have that standard.

**Comment by cwensley** [comment]
@cra0zy that's fair enough, we can certainly create a themed handler that uses the Drawable implementation for platforms that don't have a built-in control that is suitable.  Using the built-in controls is definitely ideal (and the purpose of Eto), so starting with that certainly would make sense.

**Comment by cra0zy** [comment]
@cwensley Should I make DocumentTabPage a child of TabPage or should I copy over the information so that they are not connected?

**Comment by cwensley** [comment]
I would make them unconnected, otherwise you would be able to add a `DocumentTabPage` to a `TabControl`, which wouldn't work.  We might also want to use a different name for these controls, though I'm unsure of what an ideal name might be.

**Comment by cra0zy** [comment]
`DocumentControl` and `DocumentPage`?

**Comment by cwensley** [comment]
Sounds good to me

**Comment by cra0zy** [comment]
I'll be submitting a PR about this very soon.

**Comment by cra0zy** [comment]
![documentcontrol](https://cloud.githubusercontent.com/assets/6773302/22854418/8a8b1452-f06e-11e6-8a16-eb7c0adf2f79.png)

**Comment by cwensley** [comment]
Now fully implemented, thanks @cra0zy for your work on this!

Drag to reorder, icons, etc are now all implemented in the themed handler.  Also added `AllowReordering` property and `PageReordered` event.  Setting `Enabled` to `false` will also disable changing or reordering tabs.
