### ISSUE TITLE
Getting the final image from a Drawable

### ISSUE THREAD

**Issue by LukeZerafaOfficial** [picoe/Eto#2274]
So i have a Drawable object and i was wondering if I am able to extract the final draw image as bitmap. I do not see any methods that can be called to this although be wrong. Any way i can do this?

**Comment by allsorts46** [comment]
The drawing done to a Drawable is not actually persisted anywhere - you are drawing temporarily onto the surface of the control but this can be erased and need to be redrawn at any time, which is why you have to implement either OnPaint or attach a Paint event handler. So, there isn't a 'final image' bitmap to extract.

You can however reuse the same drawing code you use for painting the Drawable to draw directly onto a bitmap. Normally in OnPaint or a Paint event handler you get a PaintEventArgs which has a Graphics object in it, and do you drawing with that. To create a bitmap and get a Graphics from it:

```
var Output = new Bitmap(500, 500, PixelFormat.Format32bppRgba);
using(var graphics = new Graphics(Output))
	{
	// Draw stuff on the graphics, like in OnPaint/Paint
	}
```

If the size needs to match the Drawable size you can get that from Drawable.Size.

It would be possible to add a method to Drawable to do this automatically for you, but that does require modifying Eto source code. You can do it without modifying the base source via a derived class like this:

```
public class CapturableDrawable : Eto.Forms.Drawable
	{
	public Bitmap PaintToBitmap()
		{
		var Output = new Bitmap(Size, PixelFormat.Format32bppRgba);

		using (var graphics = new Graphics(Output))
			{
			// Maybe clear to a solid background of known colour
			graphics.Clear(Brushes.White);

			// Call the usual painting code, but it will go on the bitmap instead of the control
			var FakePaintArgs = new PaintEventArgs(graphics, new RectangleF(PointF.Empty, Size));
			base.OnPaint(FakePaintArgs);
			}

		return Output;
		}
	}
```

**Comment by LukeZerafaOfficial** [comment]
I see, so you draw an a bitmap which then draws over to the drawable cell. Thank you for the reply.
