### ISSUE TITLE
Include support for embedded chromium into ETO

### ISSUE THREAD

**Issue by slothbag** [picoe/Eto#253]
Hi,

I have been using the embedded WebControl in Eto as my main UI and it works great, the only problem is on Windows it uses Internet Explorer which can sometimes have compatibility issues.

How hard would it be to include cross platform support for the Chromium Embedded library?  It will obviously have the dependency of the CEF library files on each platform.

**Comment by cwensley** [comment]
It would not be able to be included in the core (due to the size of CEF and associated dll's), but a supplemental set of libraries could potentially be created.  This is only really necessary for windows though, as the built-in browser for OS X and Linux are both webkit and very compatible.

If you are looking for how to use CEF from an Eto.Forms app now, you can take a look at [JabbR.Desktop](https://github.com/JabbR/JabbR.Desktop), which has implementations for CefSharp, CefGlue, and Awesomium for windows

**Comment by cwensley** [comment]
Moved to Eto.Toolkit.
