### ISSUE TITLE
When removing an item from a sorted FilterCollection by index, it gets removed at the wrong (opposite) index in a GridView

### ISSUE THREAD

**Issue by Jojatekok** [picoe/Eto#282]

**Comment by cwensley** [comment]
Thanks for the report!  Would you be able to provide a small example that shows this behaviour?  I'd like to make sure I test it correctly for your situation.

**Comment by Jojatekok** [comment]
Here is the example application for issue #279, #280, and #282: https://mega.co.nz/#!TcBC2YIL!GvB1nLyDcklyFeIx4C9Naqs7OHSVPBOaXJO9scsuKGU

**Comment by cwensley** [comment]
Thanks for reporting this!  Just a note though, that if you want to update the collection based on its *original* indexes, you need to create your own ObservableCollection<T> and pass that into the FilterCollection's constructor.  Any updates to your collection should be reflected in the FilterCollection (and vice versa).
Any edit operations you make on the FilterCollection are based on its sort and filter.  This is because if you filter the collection, or do sorting, the FilterCollection (externally) should match those rules to anyone using it.

This means your code here, actually is working as expected:

```c#
// Issue #282
collection.RemoveAt(2);
collection.Insert(2, new MyPoco { Id = 3, Text = "Row #4 -> Inserted into the correct place, but Row #48 is missing" }); // Works as expected
```

When you remove at index 2, the FilterCollection is sorted in descending order, so it will remove item 48, which is correct.  Also, you can insert pretty much anywhere you want, and it will still show up in the same spot because it has sorting applied - so inserting with an index isn't really necessary there.

Instead, you'd do this:

```c#
var collection = new ObservableCollection<MyPoco>();
var filtered = new FilterCollection<MyPoco>(collection) { Sort = (x, y) => y.Id.CompareTo(x.Id) };

//.. modify the collection, which will update the filtered view automatically.
```

Hope this helps!
