### ISSUE TITLE
When holding the up/down buttons of a NumericUpDown on Linux, values start to skyrocket

### ISSUE THREAD

**Issue by Jojatekok** [picoe/Eto#287]
This behavior is not present when only pressing the buttons 1 or 2 times.

**Comment by cwensley** [comment]
Looks like this is "default" behaviour since the default PageSize is 10, which the spinner will increment by if you hold the button down.  I typically like to keep things at their defaults which you can change using styles like so:
```c#
Style.Add<NumericUpDownHandler>(null, h => h.Control.Adjustment.PageIncrement = 1);
```
However, the default here is pretty insane (especially on linux), since it tends to go *way* too fast.  On OS X, even though it eventually increments by 10 as well, it doesn't go nearly as fast.

I might look into adding a PageSize property as well so this can be controlled, though I don't think any platform other than GTK supports it so it might not be worth it.
