### ISSUE TITLE
In Gtk, pressing the AbortButton of a Dialog doesn't close the Dialog

### ISSUE THREAD

**Issue by Jojatekok** [picoe/Eto#316]
When clicking on an AbortButton, it should close with the default value of the Dialog result's type.

**Comment by cwensley** [comment]
the AbortButton is only used so that when you press the system-defined dialog abort key (e.g. escape), then the button gets clicked automatically.  You still have to wire up the Click event on the AbortButton to close the dialog.

If other platforms close the dialog without doing this, that may be a bug.

**Comment by Jojatekok** [comment]
WPF actually closes the dialog when the AbortButton is pressed.
