### ISSUE TITLE
On the MonoMac platform, auto-sizing of Windows are faulty

### ISSUE THREAD

**Issue by Jojatekok** [picoe/Eto#326]
Some content of the Window gets cut whether I set its MinimumSize property. Even if the dimension to be auto-sized is set to 0, unwanted clipping of important controls occur.

**Comment by cwensley** [comment]
Thanks for the report!  Do you have a sample that reproduces this?

**Comment by Jojatekok** [comment]
Yes, sure, multiple examples:

- https://github.com/Jojatekok/MoneroGui.Net/blob/3ce4fba383ae2f4ba96acea57ea9dcf935e56a63/Source/MoneroGui.Net.Desktop/Windows/AccountUnlockDialog.cs -> this.SetWindowProperties(x, y) sets the Window's Title and MinimumSize
- https://github.com/Jojatekok/MoneroGui.Net/blob/3ce4fba383ae2f4ba96acea57ea9dcf935e56a63/Source/MoneroGui.Net.Desktop/Windows/OptionsDialog.cs

**Comment by cwensley** [comment]
Great, thank you!  I'll take a look.

**Comment by Jojatekok** [comment]
Thanks! :+1:

**Comment by Jojatekok** [comment]
Also, some people get the following exception when trying to launch my MonoMac app:

    The operation couldn’t be completed. (OSStatus error -67062.)

_(Source: https://bitcointalk.org/index.php?topic=683365.msg11011840#msg11011840)_

**Comment by cwensley** [comment]
The app doesn't run because you've zipped the .app which includes the __MACOS folder (which include permissions for each of the files) from your computer.  When the user right clicks to open (because your app isn't signed by an identified developer), the user doesn't have permission to update the flags on the executable to mark it as safe to open.

Easiest way is to zip it from windows or by following [these instructions on OS X](http://stackoverflow.com/questions/10924236/mac-zip-compress-without-macosx-folder)

**Comment by Jojatekok** [comment]
Awesome advice, thank you! :)
