### ISSUE TITLE
Support for an OpenGL Render Control.

### ISSUE THREAD

**Issue by azunyuuuuuuu** [picoe/Eto#39]
In short: is there any kind of OpenGL Render Control planned which is being used in conjunction with OpenTK?

**Comment by benklett** [comment]
Is this OpenGL Control in a usable state?

**Comment by cwensley** [comment]
I haven't tried it out so I'm not sure, though I've seen screenshots of it working in SharpFlame.. @bchavez, do you have more info about the state of your OpenGL control?

**Comment by bchavez** [comment]
* `Eto.Gl` - The *Eto Control*, but I haven't really formalized the API yet.
* `Eto.Gl.Windows` - Platform-specific GL should work as-is on windows using `Eto.Gl`.
* `Eto.Gl.Linux` - Platform-specific GL on Linux needs updating due to some new new **eto** changes. Shouldn't be hard to update, just haven't had enough time.
* `Eto.Gl.Mac` - Somewhat difficult *gotcha* issue I still need to resolve.

The one major issue on Mac/OSX is, by default, new GL contexts created within the same app is not shared (per surface). This means, you get an isolated GL context per surface. IE: If you have an app that uses multiple GL surfaces you will need to load textures `n` times per surface, taking up `n` times the amount of texture memory.

This behavior is different on Linux and Windows, by default, new OpenGL contexts are shared (within the same app) per surface. So, if you have multiple GL surfaces (on Linux or Windows) within the same app and load textures, you're only loading them once not `n` times per surface.

Some of the hacking attempts I've made to get it to work on Mac are `MacGLView1-7.cs`:
https://github.com/bchavez/SharpFlame/tree/eto/source/Eto.Gl.Mac

Eventually, I (or someone else) will nail down the problem so the behavior is consistent cross-platform. Just haven't had enough time atm.

**Comment by bchavez** [comment]
The OSX doc for the issue is here:

https://developer.apple.com/library/mac/documentation/GraphicsImaging/Conceptual/OpenGL-MacProgGuide/opengl_contexts/opengl_contexts.html

**To clarify, by "GL context" I mean, specifically, GL resource contexts**. (Shared object state as described in the link above).

**Comment by benklett** [comment]
Thanks for the clearification. I already tried to get it working on Windows and Linux.
Windows is working fine with Wpf, but on Linux with Gtk#2 it does not want to work: http://hastebin.com/okewirerem
Here is the code if you want to have a look at it: https://github.com/PowerOfCode/Eto/tree/opengl-control/Source/Eto.Gl.Gtk

**Comment by benklett** [comment]
I found out it has something to do with text rendering. If you have some other control on the layout, which renders text, it instantly crashes. If the text of that control is instead empty, it does not crash.

Wow, that is weird.

**Comment by kniteli** [comment]
@benklett 

I ran into the same problem. If you've still not come across the fix, you have to put this as the first line of your gtk program:

```C#
[STAThread]
public static void Main(string[] args)
{
	//this MUST be the first line in the program or any text + the opengl window will cause it to segfault
	OpenTK.Toolkit.Init ();
       ....
```
This is because of some wacky thing with x_multithreading or something, so OpenTK has to get in there before gtk initializes. Not strictly the first thing you have to do, but pretty early.

**Comment by benklett** [comment]
Thank you so much for your help I will have to try if that works when I get home.

**Comment by shabadan** [comment]
Any update on the OpenGL control for eto?

**Comment by DanWatkins** [comment]
Looks promising: https://github.com/philstopford/etoViewport.

**Comment by philstopford** [comment]
Re. etoViewport, it could do with WPF and GTK3 support, but GTK3 puzzles me as to how to proceed - it's not obvious how to set up the Cairo context needed (to me).

**Comment by cra0zy** [comment]
Duno how etoViewport is doing it, but Gtk 3 has a GLArea widget for OpenGL rendering: https://developer.gnome.org/gtk3/unstable/GtkGLArea.html

**Comment by feliwir** [comment]
Any updates on this one?

**Comment by cwensley** [comment]
@feliwir etoViewport works as of now for at least WPF, WinForms, and macOS.  I'm not sure the status of GTK though.

**Comment by philstopford** [comment]
GTK is working in my tests under VirtualBox/CentOS 7.x and also VMWare/Linux Mint. There can be some driver oddness, particularly under VirtualBox, where the OpenGL control seems to float above all other windows. I think this might be a bug in VirtualBox, though, as it is not seen in VMWare.

**Comment by feliwir** [comment]
@philstopford I don’t like the dependency to OpenTK any plans to remove it/ allow a custom callback for context creation?

**Comment by philstopford** [comment]
I'm sorry you don't like it, but I'm not seeing why. Patches are welcome, if the current approach isn't working for you. I haven't really a plan to change it myself : OpenTK has been a reliable workhorse. Earlier OpenGL efforts, I used SharpGL and then that project became abandoned. By contrast, OpenTK is actively maintained and multi-platform.
