### ISSUE TITLE
Xamarin license

### ISSUE THREAD

**Issue by SethTurin** [picoe/Eto#398]
I'm a little confused about how the Xamarin stuff works with licensing. Since eto uses xamarin libraries, does that mean we need to pay for a xamarin license to use that part of eto?

**Comment by cwensley** [comment]
Hi Seth,

You are right in that if you want to use any of the Xamarin platforms, you will need a Xamarin license for them.  These are the iOS, Android, or XamMac/XamMac2 platforms.

On Mac, if you want to deploy to the Mac App Store, you will need to use XamMac and a license.  Otherwise, you have a few free options:

1. Use MonoMac (Eto.Mac), which requires that users install mono for your application to run. 
2. Use MonoMac and embed mono in your app. You must allow your users to swap out the mono runtime if you wish to satisfy the LGPL license of the mono runtime. IANAL, so you'll have to do your own homework on that.  This is also rather complicated to do.

In the near future I hope to provide a coreclr/corefx-backed port of Eto, which will allow you to embed the runtime with no restrictions as the runtime is MIT licensed.  There's still a few outstanding issues with CoreCLR that will be needed for this to work, but I am hopeful that this will be the preferred way to target the Mac in the future.  It may also be useful for linux in the future, but that is much farther out.

Hope this helps!
Curtis.

**Comment by SethTurin** [comment]
Thanks for the response. After a little more research, it looks like all mobile mono stuff is commercial only. Oh well :)

**Comment by cwensley** [comment]
yeah there's no way around that for mobile I'm afraid.  One day maybe coreclr and .net native will be usable on iOS and Android, but that is probably very far off.
