### ISSUE TITLE
Integrate webkitgtk3-sharp within Eto forms Gtk 3 backend

### ISSUE THREAD

**Issue by cra0zy** [picoe/Eto#426]
What I am suggesting here is to add cs code of webkitgtk3-sharp to Eto Gtk 3 code so that no external dll is needed.

Repo for webkitgtk3-sharp: https://github.com/openmedicus/webkitgtk3-sharp

It's MIT License: https://github.com/openmedicus/webkitgtk3-sharp/blob/master/COPYING

**Comment by cwensley** [comment]
Thanks for the suggestion!  Though I don't know if this is the right approach to this problem as it goes against the linux philosophy (micro vs macro packages).  I would recommend instead to push to get webkit3-sharp added for gtk3 in the various linux distros.

In the meantime, you can use the precompiled webkit-sharp.dll from eto's Libraries directory [here](https://github.com/picoe/Eto/blob/develop/Libraries/GtkSharp3/webkit-sharp.dll), or compile it from source.

That being said, this still might be a good idea until such time that it is more widely available on various linux distros.  

However, my only concern is I'd hate to have to maintain the webkit binding indefinitely as it'll be a big distraction from working on Eto.Forms.  I imagine there would be a lot of busywork getting this working on various distros when native library versions are different or have different library names due to various conventions.

**Comment by cra0zy** [comment]
Found a repo for Ubuntu that offered webkitgtk3-sharp https://launchpad.net/~rebuntu16/+archive/ubuntu/sparkleshare+unofficial

**Comment by cra0zy** [comment]
Closing because NativeGtk and also I am almost done with the new WebKit 2 version for Gtk 3 that does use custom wrappers.
