### ISSUE TITLE
Code Preview option not working

### ISSUE THREAD

**Issue by cra0zy** [picoe/Eto#441]
It's giving an error:
```
Cannot find reference assemblies folder
```
![cfrasf](https://cloud.githubusercontent.com/assets/6773302/12262968/d8c2cd52-b92b-11e5-8c7b-51bfa6c463b5.png)

Xaml is working fine.

**Comment by cwensley** [comment]
Did you install the referenceassemblies-pcl package?

**Comment by cra0zy** [comment]
> Did you install the referenceassemblies-pcl package?

Yes.

**Comment by cwensley** [comment]
Hm, ok.  A little more info about your OS would help, distribution, version, what version of mono and monodevelop you have installed, and from where, etc.

Thanks!
Curtis.

**Comment by cra0zy** [comment]
Ubuntu 15.10, mono(4.2.1) and monodevelop(5.10) from Xamarin debian repo

**Comment by cra0zy** [comment]
@cwensley I wanted to ask you something, why dd you do top/bottom split? Wouldn't left/right split make more sense since you could see more code at any given time?

**Comment by cwensley** [comment]
@cra0zy, mainly because it is the default split when designing xaml interfaces in VS (and personal preference).  I do intend to add extra options to change the split to vertical, pretty much like VS' xaml designer.. I just haven't got to that yet, so thanks for asking as it increases the priority for me to work on it. (;

**Comment by cwensley** [comment]
Should now be fixed, thanks to @ermshiperete.

**Comment by cra0zy** [comment]
:D
