### ISSUE TITLE
Proposal: Add (click) handlers to Button and ButtonToolItem constructor like Command has it

### ISSUE THREAD

**Issue by firda-cze** [picoe/Eto#446]
It was proposed for roslyn to add event subscription to object initialization, which would solve it nicely, but untill then, `Command` is the only way to add button onto toolbar with lambda, but not possible for `Button`. It would as well be nice to enable `Command` support in `Button` just like `ButtonToolItem` has it.

It is easy for `Menu` and `ToolBar` thanks to `Command` and implicit conversion:

			Menu = new MenuBar() {
				Items = {
					new Command( ( s, e ) => { ...; } ) { MenuText = "..." },

but not possible for e.g. `StackLayout` and `Button`

			Content = new StackLayout() {
				Items = {
					new Button( ( s, e ) => ...

**Comment by cwensley** [comment]
Yeah I was hoping that C#6 would have addressed this as well.  That's why I added the 'With' extension, which can be used like:

`new Button { ... }.With(c => c.Click += (s, e) => ...)`

However, I agree that controls like Button/ButtonToolItem/etc should have a specific constructor that takes the delegate to make this much more succinct.

**Comment by firda-cze** [comment]
Ahh, didn't know you have `With` extension method, will try, thx.
