### ISSUE TITLE
ToolItem / MenuItem visibility

### ISSUE THREAD

**Issue by cra0zy** [picoe/Eto#450]
It would be useful if ToolItem / MenuItem would have a visibility property.

**Comment by cwensley** [comment]
Good suggestion!  It is a little more complex on Mac for this as it'll have to add/remove from the submenu (there is no way to hide an item otherwise), but it is doable.

**Comment by cra0zy** [comment]
> it'll have to add/remove

That is what I am doing right now.

**Comment by cwensley** [comment]
Ok this only got a wee complex with the macOS Toolbar, but not really all that bad at all.  I didn't realize NSMenuItem already had a Hidden property.. maybe it was hiding on me. (;  Otherwise this was pretty straightforward.  

Thanks again for the suggestion!  Give it a try and let me know if you run into any issues.

**Comment by harry-cpp** [comment]
:D
