### ISSUE TITLE
Can't compile F# project template after upgrading to .NET (or Mono) 4.5 in Xamarin for Mac

### ISSUE THREAD

**Issue by zsszatmari** [picoe/Eto#452]
Hi!

  I created a new F# Eto project based on the template. It's default created with .NET 4.0, which is not good for me (because I would like to reference some other library which needs 4.5). So I changed project setting to .NET 4.5, 'retargeted' Eto packages to 4.5, and I get error.
  Specifically, on the 'open Eto' line:

```
Error FS1108: The type 'IEnumerable`1' is required here and is unavailable. You must add a reference to assembly 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. (FS1108) (GearPlayer.Mac)
```

  Oddly enough, it works with the C# template. There is no System.Runtime checkable in the edit references dialog, neither in the F#, nor the C# project (I think this is because it's mandatory anyway).
  Could you please help me out? 
  Thanks!

**Comment by cwensley** [comment]
Hi, thanks for reporting the issue!

This problem is known (hence is why the templates create a .NET 4.0 projects). It is due to the MonoMac project type, which does not support compiling a F# project that uses PCL libraries.  The XamMac projects should work though.  Unfortunately, Xamarin is no longer supporting the MonoMac project type, and the source is no longer open source, so there's no way to get this to work without as-is without poking Xamarin and hoping they fix it.

However, I've been working on a solution that will be using the Eto.Platform.Mac.Template nuget package on a standard F# application project.  This would also allow the VS templates to work directly in Xamarin Studio.

**Comment by zsszatmari** [comment]
Thanks for looking into this, much appreciated!

**Comment by cwensley** [comment]
No problem.  I forgot to mention, you could probably get around this for now by creating a c# MonoMac project that consumes your F# library with all your common code.

**Comment by zsszatmari** [comment]
Yeah, got it!

**Comment by cwensley** [comment]
Now fixed, the latest addin creates a .NET 4.5 F# project.  Give it a try!
