### ISSUE TITLE
Visual Studio Addin breaks ability to navigate to symbols.

### ISSUE THREAD

**Issue by DanWatkins** [picoe/Eto#497]
When the Eto.Forms Visual Studio Addin 2.2.0.3 is enabled on VS Community 2015 Update 2, I cannot navigate to symbols in my projects. The error "Cannot navigate to the symbol under the caret." is shown in a message box. Also, I cannot double click on tests in the test explorer to jump to the location in file. I get the error "Cannot open the following file: C/Folder/File.cs" in the status bar at the bottom.

This has also been an issue in previous versions of VS 2015. I have disabled all other addins except the default that are enabled with a full install of VS 2015.

The project used was a Class Library and a Unit Test Project referencing the library. Both using .NET 4.6.1. [Here is the project I tested with](https://github.com/picoe/Eto/files/233147/ClassLibrary1.zip)

Interestingly, if the file where the symbol is located is already open in a tab, you can successfully navigate to from another file. This does not work for the test explorer though.

I recently did a fresh install of VS 2015 and Windows 10 and this problem persists. The only solution is to disable the Eto.Forms addin.

**Comment by cwensley** [comment]
Hi @DanWatkins, thanks for reporting the issue!  I did run into this as well, but didn't really know why it worked some times, but not others so thanks for the analysis.  

Fortunately, I believe I fixed this in commit da7693918a4d7ef5ea19d768aa49f45b25e905ef, so the next version shouldn't have this problem.

**Comment by DanWatkins** [comment]
Hi @cwensley, glad I wasn't alone. I'll keep an eye on this when the next version is released.

**Comment by firda-cze** [comment]
How did you fix that? What was causing it?

I have same problems in my VS, probably because of my own add-in (Language Service VSIX with parser/colorizer and single file generator). **Peek** works, but **navigate-to** does not, unless I have the file opened.

The strangest thing is, that it started to work properly recenty, somehow (on my PC in company, after fresh reinstall of the whole system), but I am not sure, what is the real problem.

Thx in advance for explanation, I am really lost.

**Comment by cwensley** [comment]
Fixed with the 2.3.0.6 addin, which is now published to the addin gallery.
