### ISSUE TITLE
[Question] Setting location of controls

### ISSUE THREAD

**Issue by 0xFireball** [picoe/Eto#498]
In WinForms, I can use `myControl.Location = new Point(103, 44);`

This does not work in Eto.
What can I do instead? I am porting a large amount of Winforms UI to Eto.Forms.

**Comment by cwensley** [comment]
Hi @0xFireball, you can use the `PixelLayout` to add controls at specific positions.

It is certainly not recommended to use this to layout standard controls, since they may have different default sizes depending on the platform.  However, it may be a good option to port existing code.

Cheers!
Curtis.

**Comment by 0xFireball** [comment]
Thanks! I got everything working with `PixelLayout`.
Additionally,
It is kind of tedious to position everything by code.
Are there any plans for some sort of designer?
Maybe like MonoDevelop's Stetic GUI Designer?

Thanks,
0xFireball

**Comment by cwensley** [comment]
There is a designer that comes with the XS and VS Eto.Forms addins that works for xaml, json, and code views, but it does not currently support drag/drop. I'm not planning to add drag/drop at this point, but contributions would be welcome.

**Comment by 0xFireball** [comment]
I am currently building my own UI framework as well. I have the design through code working; I can do this (an excerpt from a `Form`-like class:

<pre>
var fooLabel = new Label
{
    Text = "Hello, World!"
};
this.Controls = new Layout
{
    fooLabel,
};
</pre>

I would like to add XAML layout, however. I know that Eto supports XAML and JSON layout, but I am unsure of how to implement this. Could you give me a high-level overview of this? Additionally, I cannot use the System.Xaml namespace as I am using JSIL.

**Comment by cwensley** [comment]
I assume this has been answered so closing.  Thanks again!

**Comment by 0xFireball** [comment]
Sure, this issue can be closed, but my above question was unanswered, and I am still curious. For continuity, I will paste it in this answer.

I am currently building my own UI framework as well. I have the design through code working; I can do this (an excerpt from a `Form`-like class:

<pre>
var fooLabel = new Label
{
    Text = "Hello, World!"
};
this.Controls = new Layout
{
    fooLabel,
};
</pre>

I would like to add XAML layout, however. I know that Eto supports XAML and JSON layout, but I am unsure of how to implement this. Could you give me a high-level overview of this? Additionally, I cannot use the `System.Xaml` namespace or assembly as I am using JSIL, and System.Xaml does not decompile well.

**Comment by cwensley** [comment]
Hey @0xFireball, 

Apologies!  I went through the issue way too fast and missed that detail.  However, I'm not sure exactly what you are asking here.  Are you asking for a high level overview of how to use Xaml or Json with Eto? 

Additionally, Eto's Xaml implementation now uses [Portable.Xaml](https://github.com/cwensley/Portable.Xaml) instead of System.Xaml so you may have better success with that and JSIL.
