### ISSUE TITLE
Mac : Info.plist trouble

### ISSUE THREAD

**Issue by philstopford** [picoe/Eto#522]
With reference to the project here (https://github.com/philstopford/etoViewport), I'm running into trouble with the Mac side of things.

1) Grab that project.
2) Rename the Mac_GUI_testing folder inside Mac so that it can't be found.
3) Open the solution (either will do here)
4) Remove the Mac_GUI_testing project from the solution.
5) Add a new console project called 'Mac_GUI_testing'
6) Apply the Eto Forms sample project package from nuget and replace the source files when prompted.
7) Build and run the Mac_GUI_testing project. It will come up without issue.

8) Now add in the source files from the renamed Mac_GUI_testing folder (step 2), replacing the existing ones. You'll probably need to add the OpenTK package from nuget as well, and may also need to update the package in the Eto.Gl.\* projects

9) Build and run the Mac_GUI_testing project. It should build without complaint, but the console reports this error when it comes to try and run the application:

2016-06-01 17:06:16.206 mono[31006:1957521] No Info.plist file in application bundle or no NSPrincipalClass in the Info.plist file, exiting

I'm not sure why adding the source files like this breaks the ability for the application to be correctly bundled/run.

**Comment by cwensley** [comment]
I believe this is because you are creating a _console_ application, which cannot be run directly from Xamarin Studio.  In Eto 2.3, it will now fall back to GTK2 so it should actually run, but in 2.2 it wouldn't test if it was running in an .app bundle before selecting the Mac platform. 

In your scenario, the nuget packages will create an .app bundle for you in the output folder, but you have to run that outside of Xamarin Studio for it to run. If you want to run the Mac or Xamarin.Mac platforms from within Xamarin Studio, you need to create a MonoMac or Xamarin.Mac _application_, then add the appropriate platform from nuget.

If you're still running into problems, let me know but I'll be closing this for now.

Thanks for reporting the issue!

Cheers,
Curtis.
