### ISSUE TITLE
Xamarin Studio 6 Add-in support

### ISSUE THREAD

**Issue by DanWatkins** [picoe/Eto#527]
The Eto add-in does not appear to be available for Xamarin Studio 6 on Windows. Do I need to add a repository? Haven't tested on Linux or Mac yet.

**Comment by cwensley** [comment]
Hi @DanWatkins,

The addin hasn't been adapted for Xamarin Studio 6 yet.  It will take some work as they changed pretty much everything.  Thanks for reporting the issue!

**Comment by tpitman** [comment]
Until this is supported is there a work around for how to quick start a Xamarin Mac application?

**Comment by boonkerz** [comment]
same question here

**Comment by cwensley** [comment]
Hi @tpitman & @boonkerz , this [wiki page](https://github.com/picoe/Eto/wiki/Running-&-Debugging-a-Mac-application-in-Xamarin-Studio) should give you some detail how to do that.  Note that you can just add the appropriate nuget packages instead of referencing the .dll's directly.

**Comment by tpitman** [comment]
Step one is this:

Create a new Empty Xamarin.Mac or MonoMac application

I don't see an "Empty" Xamarin.Mac app as a template.

Here is what I have:

![image](https://cloud.githubusercontent.com/assets/2906563/16879361/88afc328-4a6d-11e6-8f11-4cdfee36f561.png)

If I choose Cocoa app then it adds all the xib and supporting GUI stuff. If I then continue down that path in the link you referenced (which I did before starting this thread), then I get an exception:

Could not detect platform. Are you missing a platform assembly?

I followed the instructions on that wiki _exactly_, excepting using Cocoa app instead of Empty app because I don't have an Empty app template.

Thoughts?

**Comment by cwensley** [comment]
@tpitman ah, right you are running into a problem with 2.2 and auto-detection (this is already fixed for 2.3, but not yet released).  Sorry, I forgot that was still an issue.

In your Program.cs, you need to pass the platform to the Application constructor, like so:

```c#
new Application(Eto.Platforms.XamMac2).Run(new MainForm());
```

Hope that helps!

**Comment by tpitman** [comment]
That solved it!

**Comment by claunia** [comment]
Should be updated for Xamarin 6.1 right now.

**Comment by nast90210** [comment]
I don't found any way to build addin from source

**Comment by cwensley** [comment]
Xamarin Studio 6.x add-in is now published to stable!

Note that Xamarin Studio 6.1.1 has a bug where it doesn't show any of the addins compatible with 6.x.  You need to manually add the following feed to your repository list:

http://addins.monodevelop.com/Stable/6.1/main.mrep
