### ISSUE TITLE
Xamarin Studio Templates: Xaml forms and dialogs missing?

### ISSUE THREAD

**Issue by vinidiktov** [picoe/Eto#601]
I want to add a xaml form with code behind to my project in Xamarin Studio 6.1.2 (macOS), but all I have listed for Eto.Forms in file templates is the following: Dialog (C#), Form (C#), Panel (C#), Panel (Json), Panel (with form preview), Panel (Xaml).

I have eto.forms add-in version 2.3.0.6 installed.

**Comment by cwensley** [comment]
Hi @vinidiktov,

Thanks for reporting the issue.  You are right in that there aren't templates for a Xaml Form or Dialog in Xamarin Studio.  Unfortunately, XS doesn't provide a way to use a wizard or customize the UI when creating new files so they have to be done manually.  We should definitely add those as templates though.

In the meantime, you can create a Xaml-based Panel, then just change its base from Panel to Form or Dialog.

Hope this helps!

**Comment by vinidiktov** [comment]
Thanks, @cwensley !

Changing the base from Panel to Form does work.

**Comment by se5a** [comment]
I've attempted to add the missing template files on my fork here: 
https://github.com/se5a/Eto

I've not yet made a PR for it as I've not yet been successful building the addon in linux, so I've not been able to test them. 

the commits add templates for CS, FS and VB, as well as adding them to the project, and added the references to the xft.xml files in the /Manifest.addin.xml. 
The VB references are inside the commented out block in that section. ( https://github.com/se5a/Eto/blob/develop/Source/Addins/Eto.Addin.XamarinStudio/Properties/Manifest.addin.xml#L36 )

While I *think* I've got everything, this needs to be built and tested before I can do a PR for it, it's quite possible I've done something silly since I was pretty much cargo culting a lot of it. 

On a related note, I may have found a bug in one of the existing FC files here: https://github.com/picoe/Eto/blob/develop/Source/Addins/Eto.Addin.XamarinStudio/Templates/Files/FS/code/panel.preview.xft.xml#L16 
I'm guessing that ```panel.code.eto.fs``` should be ```panel.preview.eto.fs```

**Comment by cwensley** [comment]
Should now be fixed with #974.  I added new file templates for dialog/form/panel for both C# and F#.  MD doesn't support a sane version of VB so those were removed.  A new version of the addin will be published along with the 2.4 release, or you can build it manually.
