### ISSUE TITLE
[Question] Why do WinForms and Direct2D exist?

### ISSUE THREAD

**Issue by SlowLogicBoy** [picoe/Eto#619]
Is there a reason for WinForms and Direct2D support to exist?
Don't get me wrong I like how WinForms works, better, than WPF, but removing support for those platform you would save so much time and effort, that could go to other platforms.

(sorry if this question was already asked, I haven't found the answer)

**Comment by cwensley** [comment]
Hey @SlowLogicBoy,

Thanks for the inquiry, it has come up once or twice before but it's been a while since someone has asked.  WinForms exists mainly as a legacy since it came before WPF and it took a while for Eto's WPF implementation to have all its kinks worked out.  Direct2D was created to provide better quality drawing than GDI, and for scenarios where performance is paramount (e.g. thousands of elements on a Drawable).

There's a few reasons to keep WinForms:
- Embedded scenarios where WPF isn't available (though latest windows embedded does support WPF afaik)
- When you have an existing win32 or WinForms app and you want the Eto.Forms forms to appear/work the same

Direct2D on WinForms on the other hand has very little reason to exist now, however I have plans in the future to transition this to work on top of WPF instead of WinForms.  The main reason for this, is that WPF's drawing infrastructure is a retained graphics system which has big performance penalties in certain scenarios (large Drawables).  There are also some _serious_ performance problems with WPF's PathGeometry when drawing a line with many jagged line paths (don't ask me why, it's probably something to do with the miter, but nothing can be done to fix it afaik).

I do foresee dropping WinForms eventually, but it seems that people still use it quite often even though WPF is the default when creating new Eto.Forms apps.  If anyone has any input about the subject, it'd be nice to hear any opinions on whether or not WinForms is indeed worth it.

**Comment by cwensley** [comment]
Added separate issues for WinForms removal and Direct2D > WPF integration so closing this issue.

Thanks for the feedback!
