### ISSUE TITLE
GridView color of selected items when lost focus

### ISSUE THREAD

**Issue by TomQv** [picoe/Eto#624]
In Eto.Winforms the color of a selected item in a GridView stays unchanged when the GridView loses focus.
In a TreeView the color of the selected item changes from blue to gray.
I think, GridView should do the same to give a visual feedback, if it has the focus or not.
Or did I just missed that property?

Tom

**Comment by cwensley** [comment]
Hey @TomQv, 

The difference is probably because the TreeView uses the standard win32 common control, whereas the GridView (and TreeGridView) use WinForms' DataGridView, which behaves differently since it's implemented entirely in .NET.  It could also be because over the years the win32 common control has had updates to match the OS style, whereas winforms is basically stagnant.

I have tried to keep the functionality of the controls "native to the platform", as in, they work as they do out of the box, especially visually.

I would recommend using a [native style](https://github.com/picoe/Eto/wiki/Styling) to change the behaviour of the GridView on the winforms platform to your liking.

That being said, I'd accept pull requests that make the controls on winforms behave similarly to each other, but it'll have to be fairly robust; in that it would need work with various colour themes, etc.

**Comment by TomQv** [comment]
Ok, I see. The problem is the WinForms' DataGridView, which just doesn't behave like that. 
Using style would be fine for me, but I can not even find a property to change. Something like "SelectionBackColorWhenInactive" or so...

**Comment by cwensley** [comment]
You'll probably have to do something like this (untested):

```
Eto.Style.Add<Eto.WinForms.Forms.Controls.GridViewHandler>(null, handler =>
{
	var style = handler.Control.DefaultCellStyle;
	var unfocusColor = System.Drawing.Color.LightGray;
	var focusColor = style.SelectionBackColor;

	style.SelectionBackColor = unfocusColor;
	handler.Control.LostFocus += (sender, e) => style.SelectionBackColor = unfocusColor;
	handler.Control.GotFocus += (sender, e) => style.SelectionBackColor = focusColor;
});
```

Hope this helps!
Curtis.

**Comment by TomQv** [comment]
yep... this helps :-)

**Comment by cwensley** [comment]
I am assuming this was resolved for you?  I'll close the issue for now but let me know if you are still unable to get this to work as you like.
