### ISSUE TITLE
GridView slow with large amount of data (Winform and Wpf)

### ISSUE THREAD

**Issue by TomQv** [picoe/Eto#658]
Assigning a datastore with lots of rows (100000+) takes very long.
The gridview is in VirtualMode and all column-autosizing is off.
I noticed, that the whole dataset is read from db, when setting the DataStore:

IEnumerable<MyClass> mydata = GetAllData();
gridview.DataStore=mydata ;

I was expecting, that only the currently visible rows were loaded and more rows as the user scrolls the list.

Tom

**Comment by cwensley** [comment]
If you pass only an IEnumerable, then the GridView will have to enumerate over all items so it can get the count of items to show in the grid.  What I suggest is creating a class that implements IList/IList<> which can return the count, but not necessarily load all the items.

You could even implement an "infinite scroll" type IList<> that would load more from the DB when items are retrieved at the bottom of the list, then trigger an `INotifyCollectionChanged.CollectionChanged` event when it updates.

**Comment by tickstory** [comment]
Hello @cwensley,

I know this issue is a few years old but I'm having the same problem with the grid being slow. I have implemented IList<T> for my collection but I can still see that when I assign the GridView.DataStore property, the first thing is does it enumerate over the entire collection (i.e. IEnumerator<T> GetEnumerator() is being called).  This is obviously taking some time with a collection that is several hundred thousand items in size. 

Is there something I am doing wrong here?

Thanks for your help.
