### ISSUE TITLE
NativeHandle on Gtk2 not useful for OpenGL context creation

### ISSUE THREAD

**Issue by benklett** [picoe/Eto#692]
I have an Eto.Forms application (latest NuGet package 2.3.0), which is intended to use a control in which I want to draw with OpenGL.

I am using SDL2-CS for context creation and MiniTK for OpenGL bindings.

If I try to create a SDL_Window with ```SDL_CreateWindowFrom(NativeHandle)```, it crashes, because the NativeHandle is invalid in this case.

If I create the SDL_Window from ```gdk_x11_drawable_get_xid(this.ToNative(true).GdkWindow.Handle)```, it works.
The function ```gdk_x11_drawable_get_xid(IntPtr gdkDisplay)``` is imported from "libgdk-x11-2.0.so.0".

I thought the NativeHandle was intended to be used for context creation. If not, I have a workaround, otherwise it would be nice if it was set to something more useful.

Btw: If I force to use WinForms, ```SDL_CreateWindowFrom(NativeHandle)``` works.

**Comment by cwensley** [comment]
On Gtk platforms, the NativeHandle is the GTK control handle (by design).  If it were to give you the GdkWindow handle only, then it would limit its usefulness.  Further, the x11 api you mentioned does not apply to all platforms afaik (macOS uses quartz), so again further limiting what you can do with the handle.

So, if you didn't want to reference the gtk# libs, you could do this instead:

`gdk_x11_drawable_get_xid(gtk_widget_get_window(NativeHandle))`

Hope this helps!
Curtis.

**Comment by benklett** [comment]
Yes, my intention was to not depend on the gtk# libs.
Thank you for this solution.
