### ISSUE TITLE
Remove "Prefer 32-bit" from application template

### ISSUE THREAD

**Issue by mennodeij** [picoe/Eto#771]
After spending countless hours trying to find out why I get spurious OutOfMemoryExceptions in my app (which had problems allocating memory when there is literally gigabytes free), I found out that there is a new setting in Visual Studio 2015 for the "Any CPU" target, which is "Prefer 32-bit". I have no idea why you would want to prefer 32-bit in any scenario (the whole concept of this option is mind-boggling to be honest), but switching that off solved my problems.

Now, the reason that was on in the first place is that this is default ON in the Desktop.csproj project template of Eto.Forms. I think it would solve a lot of problems if it were default OFF (or if you could choose it from the project template GUI).

**Comment by cwensley** [comment]
This is currently the default for all UI apps in VS 2017 (e.g. when creating a new WPF app), so I think doing the same is reasonable for Eto.  Adding more options to creating Eto apps isn't really what I'd like to do there as it'd confuse new users, and is actually quite complex to add so many options.  I think changing your project after the fact is indeed the ideal way to do this.  

If you feel strongly otherwise, please let me know (and feel free to re-open the issue) but I think this is an edge case that probably won't affect many people.

**Comment by mennodeij** [comment]
I agree to leave it like this as it is indeed an edge case; it is just irksome that when every other vendor is moving to 64-bit (for example Apple is forcing it on iOS soon) Microsoft is doing this in my opinion backwards move.

**Comment by cwensley** [comment]
I agree completely; though I think keeping in line with what MS does with their UI apps is a good idea, since they probably have a bunch of people that have dedicated time to deciding why this is important.

I honestly think MS needs to rip the bandaid off and go 64-bit only, but that is highly unlikely and doing this is just propagating the need for 32-bit support in their OS as apps don't get the proper testing in 64-bit.

**Comment by cwensley** [comment]
Basically, I think Eto's templates should only be updated when MS changes their templates to turn this off as well.
