### ISSUE TITLE
CellEdit starts on single click

### ISSUE THREAD

**Issue by TomQv** [picoe/Eto#806]
with WinForms CellEdit in a TreeGridView starts already with a single mouseclick, very irritating.
with WPF its fine, only on the second click, edit starts.

Tom

**Comment by cwensley** [comment]
This is just how WinForms' DataGridView works.  Eto's goal isn't really to make every platform behave exactly the same, but to embrace each platforms idiosyncrasies to make it feel the same as if you were to use that platform directly. 

This is what makes Eto work well; each platform feels native because Eto doesn't try to make it do things in a non-native way.  If this isn't what you want, you can use a style to change it's behaviour (if even possible), e.g.:

```
Style.Add<Eto.WinForms.Forms.Controls.TreeGridViewHandler>(null, h => h.Control.DoSomethingToMakeThisWorkTheWayYouWant());
```
