### ISSUE TITLE
Eto raspbian (Raspberry PI/ARM)

### ISSUE THREAD

**Issue by TheColonel2688** [picoe/Eto#840]
Is Eto compatible with Raspbian (Raspberry PI/ARM) yet? I would assume it would be in theory has it would just need to bind to a GTK build that was built for the pi correct? Has this been tested? Or is there work going on in this area?

Sorry if this is the wrong place for this question. I did not know where else to ask.

**Comment by SlowLogicBoy** [comment]
Hey,

If you manage to run mono on raspbian (you need a special build of raspbian, don't remember which one though) and install required gtk sharp libraries, eto should run fine, however I haven't tested this myself.

**Comment by DanWBR** [comment]
I haven't tried running Eto on Raspbian but you can install mono normally through apt-get, I've used to run a WinForms application on it without any issues, just had to download a fixed System.Windows.Forms.dll, but that is probably fixed in the main package already. I'm upgrading my app to Eto.Forms and will get back here once I have something new.

**Comment by cwensley** [comment]
Thanks for the question!

I have successfully run Eto on a first gen Raspberry Pi using Raspbian /w soft float (so it can run mono with floating point).  afaik someone was working on a fixed float ARM port that would work on stock Raspbian, but I don't know if that was ever finished.

If we get @cra0zy's NativeGtk port working for Gtk3 then we may be able to get this to run using .NET Core instead.

**Comment by cwensley** [comment]
Well, it appears that mono 3.2.7+ has hard float capability so it should work: https://www.raspberrypi.org/forums/viewtopic.php?p=466363

Please give it a try.
