### ISSUE TITLE
MacView not handling mouse double click very well

### ISSUE THREAD

**Issue by DanWBR** [picoe/Eto#855]
Hi,

I have a custom control (SkiaSharp view) declared for the MonoMac platform as:

     public class FlowsheetSurfaceControlHandler : Eto.Mac.Forms.MacView<NSView, FlowsheetSurfaceControl, FlowsheetSurfaceControl.ICallback>, FlowsheetSurfaceControl.IFlowsheetSurface
     {
         ...
     }

Mouse click event is overriden on the platform-specific control:

       public class FlowsheetSurface_Mac : NSView, Eto.Mac.Forms.IMacControl
      {
           ...

         public override void MouseDown(NSEvent theEvent)
        {
            base.MouseDown(theEvent);
            if (theEvent.ClickCount == 2) {
                //fsurface.ZoomAll((int)this.Bounds.Width, (int)this.Bounds.Height);
            }
            else {
                _lastTouchX = this.ConvertPointFromView(theEvent.LocationInWindow, null).X;
                _lastTouchY = Bounds.Height - this.ConvertPointFromView(theEvent.LocationInWindow, null).Y;
                fsurface.InputPress((int)_lastTouchX, (int)_lastTouchY);
            }
            this.NeedsDisplay = true;
        }

         ....
     }

I've commented the part that handles a double click on the above because I've wanted to handle it from the Eto control side, i.e.

     FlowsheetControl.MouseDoubleClick += (sender, e) =>
     {
           ... random code here
     }; 

The above works for WPF, WinForms, GTK#, except for MonoMac, where it only gets executed after a right-mouse click. I mean, after double-clicking on the view with the left mouse button, the code for double click will get executed only if I follow the double click with a right click.

Not sure if I'm missing something or if this is indeed an issue, because I've noticed that handling a double click is different on Cocoa when compared to the other platforms...

**Comment by cwensley** [comment]
This is completely expected, but there is a solution.  

The way the Mac side works when attaching the mouse, keyboard and a few other events is to dynamically add a method to the class (in the objective-c runtime) when you want the event to be handled.  This is done because a) the only way to get these 'events' is to subclass in objective-c, and b) because we'd have to implement all of these events for every single control, which would be insane.

To get around this, you have a few options:
1. Add the same [MouseDown code](https://github.com/picoe/Eto/blob/develop/Source/Eto.Mac/Forms/MacView.cs#L436-L456) to your MouseDown override
2. Instead of overriding MouseDown in your control, override `Initialize()` method in the handler and then subscribe to the `Widget.MouseDown` event, like so:
```c#
protected override void Initialize()
{
	base.Initialize();

	Widget.MouseDown += (sender, e) => {
		// your custom code
	};
}
```

Hope this helps!
Curtis.

**Comment by DanWBR** [comment]
Thanks Curtis, I went through route 2 and it worked perfectly!
