### ISSUE TITLE
[Mac] row not selected and wrong RowIndex detected when right click on a GridView

### ISSUE THREAD

**Issue by msasso69** [picoe/Eto#882]
Hi Curtis,

I'd like to signal two bugs I have found in the Mac version of the GridView when I right click on it with the mouse.

1) The first one is that the row is not automatically selected (I'm not sure whether considering it really a bug but in the Wpf version the row is automatically selected so the behavior is not consistent).
2) The second one is that the row index got with grid.GetCell(e.Location).RowIndex is wrong: it is always the row index of the next row except for the last row for which -1 is returned (I assume it is a bug since the Wpf version returns the correct index).

The two bugs can be easily reproduced with the following code:

	using System;
	using System.Collections.Generic;
	using System.Linq;
	using Eto;
	using Eto.Forms;

	namespace VisualSEO.EtoFormGui
	{
		public class Program
		{
			[STAThread]
			public static void Main(string[] args)
			{
				new Application(Platform.Detect).Run(new MyForm());
			}

			public class MyForm : Form
			{
				ICollection<string> model;
				GridView grid;

				public MyForm()
				{
					grid = new GridView();
					grid.Columns.Add(new Eto.Forms.GridColumn { DataCell = new TextBoxCell(0) });
					model = new List<string>();
					model.Add("Row1");
					model.Add("Row2");
					model.Add("Row3");
					grid.DataStore = model;
					grid.MouseDown += Grid_MouseDown;

					Content = new StackLayout
					{
						HorizontalContentAlignment = HorizontalAlignment.Stretch,
						Items =
						{
							grid
						}
					};
				}

				void Grid_MouseDown(object sender, MouseEventArgs e)
				{
					if (e.Buttons == MouseButtons.Alternate)
					{
						// select the row (it does not get selected with the right click of the mouse)
						GridCell cell = grid.GetCellAt(e.Location);
						int rowIndex = cell.RowIndex;
						if (Platform.IsMac)
						{
							// looks like the RowIndex is buggy: it is always the row number +1 except for the last row that is -1
							if (rowIndex == -1)
								rowIndex = grid.DataStore.Count<object>() - 1;
							else
								rowIndex--;
						}
						grid.SelectRow(rowIndex);
					}
				}
			}
		}
	}

The two bugs are quite minor since it is easy to work around them but I though it was good to signal them to you.

Regards
Massi

**Comment by cwensley** [comment]
Hey @msasso69, thanks for reporting the bugs!  I'll take a look when I get a chance. 

In Eto, behaviour of some controls across platforms aren't always exact, as Eto tries to keep each platform's idiosyncrasies so they feel like a true native app.  On mac, it appears the 'standard' behaviour is to keep the selection when you right click on a unselected item it would put a border around the right clicked item, and act only on that single item.  E.g. try it in Mail or Finder.  

However, Eto doesn't expose this functionality so it might make sense to keep the 'native' behaviour and report the selection as the single item that was right clicked in that case.

**Comment by msasso69** [comment]
Thanks Curtis,
I didn't notice that the standard behavior on Mac is to preserve the selection (I'm a newbie on Mac ;)
I agree with you that the customer experience shouldn't be changed!
Massi

**Comment by msasso69** [comment]
Curtis,
I just found out that the problem of the wrong row (on Mac) is also present in the TreeGridView,
but this time I also noticed that the row is wrong only if the header is shown!
Basically it looks like that if the header is shown Eto returns the following row.
Hope this helps
Massi

**Comment by msasso69** [comment]
Looks like the problem is in the MonoMac, in fact when TreeGridViewHandler.GetCellAt calls the MonoMac Control.GetRow the row index is wrong.
Alternatively one possible workaround could be to remove the height of the header (if shown) to the coordinates passed to the Control.GetRow

**Comment by cwensley** [comment]
Hey @msasso69, thanks for the information though I'm not seeing this behaviour in Eto.Test.  Perhaps there's something else going on?  Are you passing the right location to GetCellAt?  Your example also appears to work for me with the latest code.

**Comment by msasso69** [comment]
Hi Curtis,
in fact it was probably a month that I was not pulling (my apologies for having opened an issue before having pulled the latest code) but I can't tell you whether it got fixed or not because now I'm not anymore able to build Eto :(
I get the following error in Eto.Mac/Forms/DataObjectHandler.cs (introduced 13th Dec 2017):
![image](https://user-images.githubusercontent.com/21080030/34716348-e2baca52-f52f-11e7-928f-33eb998b049a.png)
I'm using XS 6.1.2 (build 44) and Mono 4.8.1 (mono-4.8.0-branch/22a39d7)
Any idea of what should I update in order to be able to build again on my Mac machine?
Thanks a lot for your kind support

**Comment by msasso69** [comment]
Hi Curtis,

yes you are right, with the latest version of Eto the issue got fixed (probably in the commit of 13th Dec 2017).
You can close the issue.
Sorry for not having pulled to the latest commit at the time of my last comment.

But now that I updated my Eto code to the latest version I bumped into a frustrating problem (off topic of the issue):
with the commit of 13th Dec the mono version I was using (v4.8.1) was not able to build the new file Eto.Mac/Forms/DataObjectHandler.cs (that's why it took so long for me to reply you),
so I updated my development Mac machine to XS v6.3 that updated mono to v5.1.4.7.
Eto built then fine but surprise surprise I'm now not able to hit any breakpoint anymore! :(
I tried to upgrade to MS2017 for Mac but with same result.
My only working debugging environnment is a VM that I kept with the old XS v6.1.2 and mono v4.8.1 that however prevents me to update to the latest code of Eto.

After a couple of days of frustrating investigation it turned out that what does not let me hit my breakpoints is the project guid 948B3504-5B70-4649-8FE4-BDE1FB46EC69 (probably belonging to Eto) in the ProjectTypeGuids of my main executable project.
The only code where I can place a breakpoint and successfully hit it is in the Eto - plc project (that is compiled with a portable runtime), placing a breakpoint in any other project has no effect.

So I have a question: what is a working development environment for Mac in terms of IDE and mono versions?
Hope you or anybody else can answer to this question and thanks a lot for your kind support.

Massi

**Comment by cwensley** [comment]
@msasso69 afaik, the debug system in mono changed from using .mdb to .pdb in v5.  You may simply have to just recompile everything to get the .pdb files generated then debugging/breakpoints should work again.

Thanks for testing the latest code, and I'm glad it's working for you!

**Comment by msasso69** [comment]
Yes, I noticed the change from .mdb to .pdb and also manually deleted all the bin and obj folders before recompiling but with no luck. I'll find a solution, no worries, thanks for your support anyway.

**Comment by seriussoft** [comment]
@msasso69,

I've seen behavior like this when the build events included GACing,
registering as COM, or copying and running built libraries to a different
directory (such as to the root directory of a project that I made myself
for instance). So, that led me to wonder if there is anything like that
going on in your environment?

I'm unfamiliar with the nitty-gritty in mono, Mac, and either VS for Mac or
the Mono Studio for Mac - add in that I don't have a Mac to play with, and
you'll see why I'm unable to test my hypothesis further.

Make sure that when running your debugger that the references are to the
projects themselves (instead of a pre-built assembly) and that you have
loaded the .pdb files into the debugger using the latest source code and
the build path your running from - because it sounds to me like the source
code and your running assemblies are different either in signature, in
identifier, and/or in location - I'm just not sure from the information
supplied just how it is different...yet.

I know that GAC (Call Assembly Cache) is a Microsoft Windows solution for
"DLL Hell" in respect to .NET... but, does the Mono implementation on Mac
have a similar concept - essentially a dedicated directory for registering
copies of built .NET/Mono libraries/assemblies so that you can run against
multiple versions of an assembly and guarantee that unless a project
specifies otherwise, it will always try to load said referenced assembly
from the "GAC" line its counterparts?

Again, my apologies, as I'm shooting in the dark here, and have no leads to
go off of but your situation reminds me of troubles I've faced before when
working with other 3rd party assemblies when debugging, especially the past
about one assembly still supporting debugger breakpoints and the notice of
mismatched project GUIDs.

A quick idea you could try if there is no GAC equivalent for Mono on Mac is
to search for all copies of the built assemblies in your drive(s) and
either archiving them, removing them (if feasible), or concealing them
temporariky. THEN, remove all references in your project(s) to any of the
assemblies you cannot attach breakpoints to and then re-adding the
references. I suggest doing this in Visual Studio and doing a
Clean-and-rebuild after removing ALL of those references against your
projects only - be them re-adding the references.

If you can't feasibly rebuild your projects in between removing references
and re-adding them because of them being too integrated in your code to
comment it all out temporarily, let me know and we can put our heads
together and brainstorm.

Feel free to pm me directly to talk about the nitty-gritty - but I'd like
to have the final solution mentioned here for others who gave the same
problem.

One last thing: if your IDE (say Visual Studio 2017 on Mac one I'm very
familiar with VS on windows) is loading any of the assemblies from this
repo for displaying "winforms" wizards or WYSIWYG functionality, then
you'll have to consider that Visual Studio will have the older "installed"
version in memory along with the old GUIDs and could also be blocking you.

Lemme know if you have any questions or if this helps - I imagine that
others mary face similar issues so I'd love for us to be able to resolve
this debugging breakpoint behavior.

Thanks,
Nate <SeriusSoft>

P.S. I'm typing this from my phone's KB (Droid), via an email reply, and
after pulling an all-nighter: so my apologies for any mispellings,
confusing word choices, or missing context.

Thanks,
Nate <SeriusSoft>

-----------------------------
Nathan VanBuskirk
ASP.NET, MVC.NET, C#, VB, VBA, ASP, PHP, Java, and C++ Developer
http://Seriussoft.com
nathan.vanbuskirk@seriussoft.com
