### ISSUE TITLE
Add ability for DrawableCell to provide desired width

### ISSUE THREAD

**Issue by msasso69** [picoe/Eto#911]
I'd like that the DrawableCell used with a TreeGridView would adapt either to the contained text or to the available width (I need both use cases).
Right now I achieve it measuring the text of every new row and set the width of the DrawableCell (for the first use case) and setting the width of the DrawableCell according to the size of the parent control after receiving its SizeChanged event (for the second use case)
Unfortunately (on Mac only) in both cases most of the times the DrawableCell width is forced to a mysterious width of 37 pixels, everything gets corrected if I manually resize the control forcing a repaint.
Is there a way to get what I need more natively?
In the following simple code I set the width as described but the problem does not seem to happen with it. Any clue of what I could do wrong in my real application?
(Note that I populate the TreeGridView after assigning the DataStore in order to see it populated live)

## Expected Behavior
DrawableCell in TreeGridView expands to fit the contained text or expands to all available width when AutoSize = true and ShowHeader = false

## Actual Behavior
DrawableCell has a fixed width of 37 pixels

## Code that Demonstrates the Problem

	using System;
	using System.Collections.Generic;
	using Eto;
	using Eto.Drawing;
	using Eto.Forms;

	namespace VisualSEO.EtoFormGui
	{
		public class Program
		{
			[STAThread]
			public static void Main(string[] args)
			{
				new Application(Platform.Detect).Run(new MyForm());
			}

			public class MyForm : Form
			{
				TreeGridItemCollection model;
				TreeGridView tree;

				public MyForm()
				{
					this.Width = 500;
					tree = new TreeGridView();
					tree.BackgroundColor = Colors.Orange;

					if (Platform.Supports<DrawableCell>())
					{
						var drawableCell = new DrawableCell();
						drawableCell.Paint += (sender, e) =>
						{
							Color color = Colors.Black;
							Font font = SystemFonts.Label();
							string text = "sfsgh rthysdgs rsths wetd shrshwrg sgegg wetrw hfd st etjteyj e wetrwggwe tsdvwsdwe dsgewwe dsr";
							SizeF size = font.MeasureString(text);

							// uncomment this for use case 1
							//tree.Columns[0].Width = (int)size.Width + 15;

							// strangely on Mac text are drawn a little bit down below, so we need to write them a little upper
							e.Graphics.DrawText(SystemFonts.Label(), color, (float)0, (float)-8, text); // Mac
							//e.Graphics.DrawText(SystemFonts.Label(), color, (float)0, (float)0, text); // Wpf
						};
						tree.Columns.Add(new Eto.Forms.GridColumn { DataCell = drawableCell, AutoSize = true });
					}
					tree.ShowHeader = false;

					model = new TreeGridItemCollection();
					model.Add(new TreeGridItem());
					model.Add(new TreeGridItem());
					model.Add(new TreeGridItem());
					tree.DataStore = model;

					// uncomment this for use case 2
					//this.SizeChanged += (sender, e) => { tree.Columns[0].Width = this.Width; };

					Content = new StackLayout
					{
						HorizontalContentAlignment = HorizontalAlignment.Stretch,
						VerticalContentAlignment = VerticalAlignment.Stretch,
						Items = { new StackLayoutItem(tree, VerticalAlignment.Stretch, true) }
					};
				}
			}
		}
	}

## Specifications

  - Version: 2.4 (latest develop branch)
  - Platform(s): Mac

**Comment by seriussoft** [comment]
I've ran into issues like this caused by other events triggering a change -
commonly, the events trigger the default size as if nothing were inside the
container, and then any custom sizing is lost - granted I've not any
experience with this on a mac specifically.

I'd suggest setting a breakpoint on the setter of the size property so you
can see what in the stack is actually reducing the size to that 37 pixel
value.

The fact that manual changes after the fact have the desired affect but the
automagic population of new cells is misbehaving really makes me lean
towards another event triggering the size change to a value representative
of an empty cell.

A semi related issue with another product on my windows 10 laptop occurred
because i had screen resolution increased to 150% on one screen (main
laptop screen duplicating on a monitor) and another screen increased to
125% screen resolution. Manual changes have after the form was drawn to the
screen behaved as expected; but custom code-based changes to cell size in a
listview, datagridview, and treeview as well as any changes to default cell
size in the property editor window of the wysiwyg winform view all produced
very odd numbers that were considerably smaller than my desired size let
alone the default size. in this scenario, even the debugger with
breakpoints set on the setter (i forced-extended the controls to debug the
issue) didn't trigger.

As soon as changed the screen resolution of both my main screen duplicated
to a monitor and my secondary/extended screen to the default 100%, the
issue disappeared.

So, if you are unable to debug, try to extend and set breakpoints. if
nothing triggers, log all events that fire on the control during automagic
cell population and compare to manual changes. If nothing seems abnormal or
stands out, check if you have any resolution oddities such as screen
resolution set to something other than 100% or larger than default font,
external monitors, etc.

that should hopefully help you diagnose the issue a little farther or even
find a solution. sadly, i don't have a Mac to test against - but those 2
scenarios seem the most likely candidates:
1. other events reseting the cell size by adding/removing cells to the same
shared size column or resizing cells agnostic of the text inside
2. a non-default/custom screen resolution setting that activates a bug at
the lowest level that might even affect the native code base that this code
relies on.

Another way to help verify #2 is if you have a windows machine, set the
resolution (not the 1900x1024 like numbers, but the of that zooms in or out
the pixels on the screen to aid people with poor vision) to 125% or 150% by
selecting those percentages using the percentage slider in the display
/graphics settings.

Hope this helps or at least gets you thinking in a way that you find the
answer and are able to share with the rest of us :)

Thanks and Happy Coding,
Nate

-----------------------------
Nathan VanBuskirk
ASP.NET, C#, and C++ Developer
http://Seriussoft.com
nathan.vanbuskirk@seriussoft.com

**Comment by msasso69** [comment]
Thanks Nate, 
scenarios 1 looks more probable to me at least in my code, I'll investigate on it.
Just a question: when you say "try to extend and set breakpoints" you mean override the default On<events>() method handlers or what?
Massi

**Comment by seriussoft** [comment]
Hello Massi,

My apologies, if you are unable to set breakpoints on the setter for the
size property of the cell because you are using the compiled lib, then my
suggestion was to extend the cell and its parents so you could place a
breakpoint - but that is a rabbit hole that will keep you busy for a long
while - I wasn't thinking clearly.

Since the code is open source, you should be able to have your ide open
against this solution, set breakpoints, build in debug mode, and have your
specific code base reference the debug build of this project - that way you
can break into the code and view the stack when the size poroperty is
changed to 37.

Just make sure that you set that filter of the incoming value ("where value
== 37") on your breakpoint. this will let you see by and every time that
the value is updated.

I haven't looked at the size property of this class yet, but if there is a
backing field for the size property you are targeting, then you can update
your breakpoint filter to say "where value == 37 && {_backing_value} ==
{the_value_you_set_programmatically}" so that you only get a ding the first
time it changes the value after you set it.

this will let you fly thru faster, but you may have to run through more
than once to catch all times that the value is updated automagically.

my guess on the events is that an external event belonging to a parent is
triggering the default size change - fast was how it usually worked in
winforms and wpf. usually something would get added and then a parent would
send a message to all its children to use default behavior or would
recreate the chrildren using a clone thereby skipping the events that
triggered desired size changes.

Thanks,
Nate

-----------------------------
Nathan VanBuskirk
ASP.NET, C#, and C++ Developer
http://Seriussoft.com
nvanbkirk@gmail.com
nathan.vanbuskirk@seriussoft.com
903-530-7851

**Comment by msasso69** [comment]
Hi Nate,

sorry if I didn't understand you at first, of course I can debug the source code instead of using the compiled lib (actually I'm already doing it ;)
Your hint anyway is very good, I'll certainly follow your piece of advice!

Thanks
Massi

**Comment by seriussoft** [comment]
Hello Massi,

Glad to hear and honestly I glad that I didn't make much sense the first
time because I might accidently have sent you on a wild goose chase. One of
the great things about open source software is often times it's quicker to
debug issues sms not only learn more about how they work but also able to
suggest solutions to the repo making fixes quicker than typical closed
source projects.

If you get stumped or find out a little bit more about what's going on
under the hood, feel free to share and I'll gladly share any ideas that
come to mind.

Hopefully there's an easy fix or there's a different but equally simple
workaround.

Cheers,
Nate

-----------------------------
Nathan VanBuskirk
ASP.NET, C#, and C++ Developer
http://Seriussoft.com
nathan.vanbuskirk@seriussoft.com

**Comment by msasso69** [comment]
Hi All,

I think I managed to reproduce the issue in a relatively small program:

If you launch the following code (1) and resize the GridColumn (2), then press the button "Hide" (3) and then the button "Show" (4) you'll see that the GridColumn is resized to the original width of 36.

Basically the Width of the column is never set. Putting a breakpoint in the setter of the GridColumn the value is set correctly but it is not rendered and the column always appears with the width of 36 (that I do not know where it comes from).
The only possibility I found to effectively set the width of the column is in the Paint event of the DrawableCell.

Here's the code:

	using System;
	using System.Collections.Generic;
	using Eto;
	using Eto.Drawing;
	using Eto.Forms;

	namespace VisualSEO.EtoFormGui
	{
		public class Program
		{
			[STAThread]
			public static void Main(string[] args)
			{
				new Application(Platform.Detect).Run(new MyForm());
			}

			public class MyForm : Form
			{
				TreeGridItemCollection model;
				TreeGridView tree;
				static GridColumn column;

				public MyForm()
				{
					this.Width = 500;
					this.Height = 300;
					tree = new TreeGridView();
					

					if (Platform.Supports<DrawableCell>())
					{
						var drawableCell = new DrawableCell();
						drawableCell.Paint += (sender, e) =>
						{
							Color color = Colors.Black;
							Font font = SystemFonts.Label();
							string text = "sfsgh rthysdgs rsths wetd shrshwrg sgegg wetrw hfd st etjteyj e wetrwggwe tsdvwsdwe dsgewwe dsr";
							SizeF size = font.MeasureString(text);

							//tree.Columns[0].Width = (int)size.Width + 15; // THIS IS WORKING :)

							// strangely on Mac text are drawn a little bit down below, so we need to write them a little upper
							e.Graphics.DrawText(SystemFonts.Label(), color, (float)0, (float)-8, text); // Mac
							//e.Graphics.DrawText(SystemFonts.Label(), color, (float)0, (float)0, text); // Wpf
						};
						tree.Columns.Add(column = new GridColumn 
						{ 
							DataCell = drawableCell, /*AutoSize = true,*/
							Width = 600 // NOT WORKING!
						});
					}
					//tree.ShowHeader = false;

					model = new TreeGridItemCollection();
					tree.DataStore = model;
					model.Add(new TreeGridItem());
					model.Add(new TreeGridItem());
					model.Add(new TreeGridItem());
					tree.ReloadData();

					//this.SizeChanged += (sender, e) => { tree.Columns[0].Width = this.Width; };
					//tree.Columns[0].Width = 600; // NOT WORKING!

					Panel panel1 = new Panel
					{
						Content = new StackLayout
						{
							HorizontalContentAlignment = HorizontalAlignment.Stretch,
							VerticalContentAlignment = VerticalAlignment.Stretch,
							Items =
							{
								new StackLayoutItem(tree, true)
							}
						}
					};
					Panel panel2 = new Panel();
					StackLayout stack = null;
					Button button1 = new Button() { Text = "Show" };
					Button button2 = new Button() { Text = "Hide" };
					button1.Click += (sender, e) => { stack.Items.Clear(); stack.Items.Add(new StackLayoutItem(panel1, true)); };
					button2.Click += (sender, e) => { stack.Items.Clear(); stack.Items.Add(new StackLayoutItem(panel2, true)); };

					Content = new StackLayout
					{
						HorizontalContentAlignment = HorizontalAlignment.Stretch,
						VerticalContentAlignment = VerticalAlignment.Stretch,
						Items = 
						{
							new StackLayout
							{
								Orientation = Orientation.Horizontal,
								Items = { button1, button2 }
							},
							new StackLayoutItem(stack = new StackLayout
							{
								HorizontalContentAlignment = HorizontalAlignment.Stretch,
								VerticalContentAlignment = VerticalAlignment.Stretch,
								Items = 
								{
									new StackLayoutItem(panel1, true),
								}
							}, true)
						}
					};
				}
			}
		}
	}

Does anyone know why?
Massi

**Comment by cwensley** [comment]
There's actually no way for pretty much any platform to determine the bounds of what drawing you've done for a DrawableCell, so you need to specify the width manually.  It'd be nice if there were a way you can supply/calculate the desired width though, which would make doing this easy.

**Comment by msasso69** [comment]
I think that this is true for the Autosize property of the GridColumn to have effect, but why also explicitly setting its Width is not working? When you say that it would be nice to have ways to calculate/supply the desired width you mean that the DrawableCell should exposed somehow the dimensions of it content?

**Comment by cwensley** [comment]
@msasso69 Hm, you're right, Width should definitely be working.  I've created #1003 to track that separately.

**Comment by seriussoft** [comment]
GDI+ had a means (as well as the Printer classes) of determining width of text using a selected font, font options, etc. It would use rules for drawing w/o drawing to the screen to give you an estimation that was 99.9% of the time correct. I thought that WinForms and WPF both had such a feature as I've done some resizings of outer containers based on what the inner containers should be. That, along with a shared column width constraint (WPF), and your grid would always size itself as necessary based on the width of the static (or dynamic/code-driven) text contents.

Would such a feature as that be plausible here? say a specific event like OnDrawing or OnSizeDetermined?

Just spitballing a bit here to see if any ideas sprout from my ramblings 😄

**Comment by msasso69** [comment]
the issue is no longer present (not at least using XamMac2), it can be closed :)
