### ISSUE TITLE
WindowsAPICodePack reference missing

### ISSUE THREAD

**Issue by RobotCaleb** [picoe/Eto#952]
I noticed that system tray support was added last year. I tested the nuget package for Eto, but it doesn't seem to be new enough.
I then grabbed the source from master by pulling down this repository as a `git submodule`.
I'm on Linux using Rider as my development environment. My supported set is Ubuntu 16.04 and Windows 7+. So I added to my solution the existing projects `Eto`, `Eto.Gtk2`, and `Eto.WinForms`.
Attempting to build these projects resulted in success for each except `Eto.WinForms`. Adding nuget package of `WindowsAPICodePack` to `Eto.WinForms` resolved my build issue.

Was this a proper fix? Should this be incorporated into this repository?

**Comment by cwensley** [comment]
Perhaps your development tools are out of date.  The latest Eto has been recently updated and will now require latest bits on all platforms (mono 5.4.x, MD/VS for Mac 7.3, VS 2017 15.5).

One thing that might be tripping you up is nuget packages are embedded as <PackageReference> instead of using packages.config.   

Also, make sure you do a package restore before trying to compile as it no longer does it while compiling.  The IDE's all do that for you, usually.

If you still can't get it to work, you could always use the daily nuget build from [myget](https://www.myget.org/F/eto/)

**Comment by cwensley** [comment]
Ah, didn't catch that you're using Rider.

See: https://rider-support.jetbrains.com/hc/en-us/community/posts/115000659910--NET-Framework-Projects-that-support-PackageReference-in-csproj

**Comment by RobotCaleb** [comment]
Thanks for looking into it further!
I've upgraded my instance of Rider and have it working using latest from master. I'll close this and ask a different question in a new issue when I've figured out exactly what I want to ask.

**Comment by turbo** [comment]
How did you get it to work? I'm using the latest Rider and the master (non-core) solution doesn't load, because of the same error in the WinForms project (can't resolve the WinAPIPack stuff).
