### ISSUE TITLE
Using latest Eto code in .NET 4.6.1 project instead of NuGet package

### ISSUE THREAD

**Issue by Telvee32** [picoe/Eto#963]
Not sure if this is the right place to post this question but I don't see any other way.
I've got a project that I'm working on that up until now had been using v2.3.0 (ie, the NuGet packages) and v0.14.0 of Portable.Xaml, this having been originally created using the VS extension. This project is now going to require the drag and drop functionality, which I don't see available in v2.3.0 as it's been a recent development.
Having removed the NuGet packages and added in the latest binaries manually (now using v0.17.0 of Portable.Xaml from NuGet as per the Eto.Serialization.Xaml-pcl project), the solution still builds but falls over (with a System.NotImplementedException coming from Portable.Xaml.ValueSerializerContext.get_Instance()) when attempting to read the .xeto file for the main form, which had been fully functional up until now.
The method call in question is just XamlReader.Load(this) within the form's constructor, which contains nothing but this one line of code.

What I did:

1. Removed the v2.3.0 Eto and Eto.Serialization.Xaml NuGet packages and updated Portable.Xaml to v0.17.0, which for some reason included downloading a load of .NET Standard packages.
2. Built the latest Eto source using VS2017.
3. Grabbed Eto and Eto.Serialization.Xaml binaries from Eto\artifacts\core\Release\netstandard1.3, and WPF and GTK3 binaries from Eto\artifacts\obj\Eto.Wpf/Gtk3\Release, copied them into my project and referenced.
4. Project builds successfully but will not run.

I strongly suspect the problem is with something I have done, perhaps version conflicts, or having simply copied the wrong binaries. Essentially all I want to do is have my project updated to use the latest Eto code instead of an out-of-date NuGet package.

**Comment by cwensley** [comment]
Hi @Telvee32, thanks for the question!

I'm doing a lot of transitioning of the code right now (past few days) to modernize the project setup and transition to .NET Standard vs the obsolete PCL.  I did actually run into the same issue just yesterday (with Portable.Xaml), and have already made a fix in Portable.Xaml v0.19.  

As part of the recent updates to Portable.Xaml, its custom TypeConverter implementation has been removed. Unfortunately, I need to do some more work on Portable.Xaml and Eto to support transitioning to v0.19 as there still is a PCL version of Eto.Serialization.Xaml which doesn't have access to TypeConverter, but is required by Eto's xaml implementation.  

The good news is this should be fixed shortly, it's just part of finishing up and polishing the 2.4.0 release.

**Comment by cwensley** [comment]
No problem.  This should now be fixed in the latest Eto develop and associated [nuget packages](https://www.myget.org/F/eto/) along with Portable.Xaml 0.20.

You can't migrate to .NET Core as none of the current platforms support running on it (gtk has support for it added 3 days ago, but no nuget packages yet).  You can however migrate to the sdk-style csproj and/or use [`<PackageReference>`](https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files), but still build for net461.

You don't have to add those dependencies directly, they will be added when you reference the associated .net standard package(s).  However, using sdk-style csrpoj or using `<PackageReference>` will only list the packages you referenced directly, instead of all of their dependencies.

Hope this helps!
Curtis.
